import { locales } from "@/features/i18n/config";
import type { DemandTier, MonetizationTier, PrivacyMode, ToolCategory, ToolComponentKey, ToolDefinition } from "./types";

const allLocales = [...locales];

const guide = (slug: string, title: string) => ({
  title,
  href: `/guides/${slug}`,
});

const seo = (title: string, description: string, keywords: string[]) => ({
  title,
  description,
  keywords,
});

const clusterByCategory: Record<ToolCategory, string> = {
  Text: "text-cleanup",
  Code: "code-formatting",
  Web: "web-debugging",
  Data: "data-conversion",
  Time: "time-scheduling",
  Security: "security-generators",
  Color: "color-css",
  SEO: "seo-webmaster",
  Network: "network-debugging",
};

const demandWeight: Record<DemandTier, number> = {
  core: 30,
  growth: 15,
  "long-tail": 5,
};

const examples = (sample: string, action: string, result: string) => [
  { label: "Common input", value: sample, note: action },
  { label: "Typical output", value: result, note: "Use this as a quick sanity check before copying results." },
];

const localFaqs = (toolName: string) => [
  {
    question: `Does ${toolName} upload my input?`,
    answer: "No. This tool runs in your browser unless the privacy badge explicitly says a server route is required.",
  },
  {
    question: "Can I use this for production secrets?",
    answer: "Avoid pasting sensitive production data into any website. Prefer local test data or redacted payloads.",
  },
];

const serverFaqs = (toolName: string) => [
  {
    question: `Why does ${toolName} use a server route?`,
    answer: "Browsers cannot perform this check reliably by themselves, so the tool sends only the entered host or URL to a small server route.",
  },
  {
    question: "Should I test private internal systems here?",
    answer: "No. Use public endpoints only and avoid private hostnames, credentials, or internal infrastructure details.",
  },
];

const tool = ({
  slug,
  title,
  shortTitle,
  category,
  description,
  component,
  keywords,
  guideSlug,
  guideTitle,
  relatedTools,
  accent = "border-zinc-500",
  demandTier = "growth",
  privacyMode = "local",
  requiresServer = false,
  aliases,
  useCases,
  inputExamples,
  contentCluster,
  monetizationTier,
  sample,
  action,
  result,
}: {
  slug: string;
  title: string;
  shortTitle: string;
  category: ToolCategory;
  description: string;
  component: ToolComponentKey;
  keywords: string[];
  guideSlug: string;
  guideTitle: string;
  relatedTools: string[];
  accent?: string;
  demandTier?: DemandTier;
  privacyMode?: PrivacyMode;
  requiresServer?: boolean;
  aliases?: string[];
  useCases?: string[];
  inputExamples?: string[];
  contentCluster?: string;
  monetizationTier?: MonetizationTier;
  sample: string;
  action: string;
  result: string;
}): ToolDefinition => ({
  slug,
  title,
  shortTitle,
  category,
  description,
  component,
  accent,
  demandTier,
  searchIntents: keywords,
  aliases: aliases ?? keywords,
  useCases: useCases ?? [action, `${title} for ${category.toLowerCase()} workflows`],
  inputExamples: inputExamples ?? [sample],
  contentCluster: contentCluster ?? clusterByCategory[category],
  monetizationTier: monetizationTier ?? demandTier,
  supportedLocales: allLocales,
  privacyMode,
  requiresServer,
  seo: seo(
    `${title} - Free Online ${category} Tool`,
    `${description} Use this free online ${title.toLowerCase()} with ${requiresServer ? "public server-side checks" : "local browser processing"}, examples, FAQ, and related tools.`,
    keywords,
  ),
  examples: examples(sample, action, result),
  faqs: requiresServer ? serverFaqs(title) : localFaqs(title),
  guides: [guide(guideSlug, guideTitle)],
  relatedTools,
});

export const tools: ToolDefinition[] = [
  {
    slug: "regex-tester",
    title: "Regex Tester",
    shortTitle: "Regex",
    category: "Code",
    description: "Test JavaScript regular expressions, inspect matches, and keep common patterns close by.",
    component: "regex",
    accent: "border-emerald-500",
    demandTier: "core",
    searchIntents: ["regex tester", "regular expression tester", "javascript regex", "regex cheat sheet"],
    aliases: ["regexp tester", "regex match tester", "regex validator", "pattern tester"],
    useCases: ["Validate JavaScript regular expressions", "Inspect capture groups and match positions", "Test practical form and route patterns"],
    inputExamples: [String.raw`^[^\s@]+@[^\s@]+\.[^\s@]+$`, String.raw`(\d{4})-(\d{2})-(\d{2})`],
    contentCluster: "code-formatting",
    monetizationTier: "core",
    supportedLocales: allLocales,
    privacyMode: "local",
    requiresServer: false,
    seo: seo("Regex Tester - JavaScript Regular Expression Tool", "Test JavaScript regular expressions, flags, groups, and matches in a fast online regex tester with examples and a cheat sheet.", ["regex tester", "regular expression tester", "javascript regex", "regex cheat sheet"]),
    examples: [
      { label: "Email shape", value: String.raw`^[^\s@]+@[^\s@]+\.[^\s@]+$`, note: "Good for simple form validation previews." },
      { label: "URL path", value: String.raw`^/tools/[a-z0-9-]+$`, note: "Checks slug-style application routes." },
      { label: "Capture date", value: String.raw`(\d{4})-(\d{2})-(\d{2})`, note: "Shows capture groups for ISO-like dates." },
    ],
    faqs: [
      { question: "Which regex engine is used?", answer: "The tester uses the browser JavaScript RegExp engine, so behavior matches modern web applications." },
      { question: "Why does a valid-looking regex fail?", answer: "JavaScript needs escaped backslashes and supports a specific flag set. Check the error panel for syntax details." },
    ],
    guides: [guide("regex-cheat-sheet", "Regex cheat sheet for practical JavaScript patterns")],
    relatedTools: ["json-formatter", "url-encoder", "text-diff"],
  },
  {
    slug: "cron-generator",
    title: "Cron Expression Generator",
    shortTitle: "Cron",
    category: "Time",
    description: "Build and explain five-field cron expressions for common scheduling tasks.",
    component: "cron",
    accent: "border-sky-500",
    demandTier: "core",
    searchIntents: ["cron generator", "cron expression", "crontab examples", "schedule generator"],
    aliases: ["crontab generator", "cron maker", "cron schedule builder", "cron expression builder"],
    useCases: ["Build common recurring schedules", "Explain five-field crontab expressions", "Copy schedule presets for jobs and automations"],
    inputExamples: ["*/15 * * * *", "0 9 * * 1-5"],
    contentCluster: "time-scheduling",
    monetizationTier: "core",
    supportedLocales: allLocales,
    privacyMode: "local",
    requiresServer: false,
    seo: seo("Cron Expression Generator - Build and Explain Cron Schedules", "Generate, inspect, and copy five-field cron expressions for minute, hourly, daily, weekly, and monthly schedules.", ["cron generator", "cron expression", "crontab examples", "schedule generator"]),
    examples: [
      { label: "Every 15 minutes", value: "*/15 * * * *", note: "Runs four times per hour." },
      { label: "Weekday morning", value: "0 9 * * 1-5", note: "Runs at 09:00 from Monday through Friday." },
      { label: "Monthly report", value: "30 8 1 * *", note: "Runs at 08:30 on the first day of each month." },
    ],
    faqs: [
      { question: "Does this support Quartz cron?", answer: "This page focuses on standard five-field crontab syntax. Quartz has seconds and extra fields." },
      { question: "Are time zones handled here?", answer: "Cron execution time zones are controlled by your scheduler or server, not the expression alone." },
    ],
    guides: [guide("cron-expression-examples", "Cron expression examples and scheduling caveats")],
    relatedTools: ["timestamp-converter", "timezone-converter", "uuid-generator"],
  },
  {
    slug: "meta-tag-generator",
    title: "Meta Tag Generator",
    shortTitle: "Meta Tags",
    category: "SEO",
    description: "Create title, description, canonical, Open Graph, and X card tags for web pages.",
    component: "meta",
    accent: "border-violet-500",
    demandTier: "core",
    searchIntents: ["meta tag generator", "seo meta tags", "open graph generator", "twitter card generator"],
    aliases: ["metadata generator", "og tag generator", "social preview meta", "x card generator"],
    useCases: ["Generate SEO and social sharing tags", "Create canonical and robots tags", "Prepare Open Graph previews"],
    inputExamples: ["Title, description, canonical URL", "og:title and og:image"],
    contentCluster: "seo-webmaster",
    monetizationTier: "core",
    supportedLocales: allLocales,
    privacyMode: "local",
    requiresServer: false,
    seo: seo("Meta Tag Generator - SEO, Open Graph, and X Card Tags", "Generate clean HTML meta tags for SEO previews, Open Graph sharing, X cards, canonical URLs, and robots directives.", ["meta tag generator", "seo meta tags", "open graph generator", "twitter card generator"]),
    examples: [
      { label: "Product page", value: "Title, description, OG image, canonical URL", note: "Best for launch pages and tools." },
      { label: "Noindex draft", value: "robots: noindex,nofollow", note: "Use only for pages that should not appear in search." },
      { label: "Social preview", value: "og:title, og:description, og:image", note: "Improves link previews in chat and social apps." },
    ],
    faqs: [
      { question: "How long should meta descriptions be?", answer: "Keep them concise, specific, and useful. Search engines may rewrite them when another snippet fits better." },
      { question: "Should every page have a canonical URL?", answer: "Yes for indexable pages, especially when query strings or alternate paths can show similar content." },
    ],
    guides: [guide("seo-meta-tags", "SEO meta tags that are worth generating")],
    relatedTools: ["open-graph-preview", "robots-txt-generator", "sitemap-generator"],
  },
  {
    slug: "iframe-viewer",
    title: "Iframe Viewer",
    shortTitle: "Iframe",
    category: "Web",
    description: "Preview URLs inside common viewport frames and copy basic iframe markup.",
    component: "iframe",
    accent: "border-cyan-500",
    demandTier: "growth",
    searchIntents: ["iframe viewer", "responsive preview", "iframe generator", "viewport preview"],
    aliases: ["iframe preview", "website preview frame", "responsive iframe tester", "embed preview"],
    useCases: ["Preview public pages in common viewport frames", "Copy iframe markup", "Check frame blocking behavior"],
    inputExamples: ["https://www.bobob.app", "390 x 844 mobile frame"],
    contentCluster: "web-debugging",
    monetizationTier: "growth",
    supportedLocales: allLocales,
    privacyMode: "local",
    requiresServer: false,
    seo: seo("Iframe Viewer - Preview Responsive Pages in Browser Frames", "Preview a URL in desktop, tablet, and mobile iframe sizes, inspect frame limitations, and copy iframe markup.", ["iframe viewer", "responsive preview", "iframe generator", "viewport preview"]),
    examples: [
      { label: "Desktop", value: "1440 x 900", note: "Useful for full-width web app checks." },
      { label: "Tablet", value: "834 x 1112", note: "Checks medium breakpoint behavior." },
      { label: "Mobile", value: "390 x 844", note: "Good for common mobile layout checks." },
    ],
    faqs: [
      { question: "Why does a site refuse to load?", answer: "Some sites block framing with X-Frame-Options or Content-Security-Policy. That is a security feature." },
      { question: "Is the entered URL stored?", answer: "No. The preview runs in the browser and the tool does not persist entered URLs." },
    ],
    guides: [guide("iframe-preview-limitations", "Iframe preview limitations developers should expect")],
    relatedTools: ["url-parser", "http-status-checker", "open-graph-preview"],
  },
  {
    slug: "lorem-ipsum-generator",
    title: "Lorem Ipsum Generator",
    shortTitle: "Lorem",
    category: "Text",
    description: "Generate placeholder copy for product mocks, forms, cards, and content layouts.",
    component: "lorem",
    accent: "border-amber-500",
    demandTier: "growth",
    searchIntents: ["lorem ipsum generator", "placeholder text", "dummy text generator", "ui mockup text"],
    aliases: ["dummy text", "placeholder copy", "lipsum generator", "sample text generator"],
    useCases: ["Generate readable placeholder copy", "Test UI card and form text density", "Build mock content blocks"],
    inputExamples: ["1 paragraph, 2 sentences", "4 paragraphs, 4 sentences"],
    contentCluster: "text-cleanup",
    monetizationTier: "growth",
    supportedLocales: allLocales,
    privacyMode: "local",
    requiresServer: false,
    seo: seo("Lorem Ipsum Generator - Placeholder Text for UI Mockups", "Generate clean placeholder text for UI mockups, content cards, form previews, and editorial layouts.", ["lorem ipsum generator", "placeholder text", "dummy text generator", "ui mockup text"]),
    examples: [
      { label: "Short card", value: "1 paragraph, 2 sentences", note: "Fits cards and compact previews." },
      { label: "Article block", value: "4 paragraphs, 4 sentences", note: "Good for testing page rhythm." },
      { label: "Form help text", value: "1 sentence", note: "Useful for dense app screens." },
    ],
    faqs: [
      { question: "Should placeholder text be used in production?", answer: "No. Replace it with real content before launch so layout and accessibility are tested honestly." },
      { question: "Why not use random gibberish?", answer: "Readable placeholder text exposes spacing and line-height problems more reliably." },
    ],
    guides: [guide("placeholder-text-for-design", "Placeholder text patterns for product design")],
    relatedTools: ["word-character-counter", "case-converter", "slug-generator"],
  },
  tool({
    slug: "json-formatter",
    title: "JSON Formatter",
    shortTitle: "JSON",
    category: "Data",
    description: "Format, minify, and validate JSON payloads without sending them to a server.",
    component: "json",
    accent: "border-orange-500",
    demandTier: "core",
    keywords: ["json formatter", "json validator", "json minifier", "format json online"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["json-to-typescript", "json-schema-validator", "jsonpath-tester"],
    sample: "{\"status\":\"ok\",\"items\":[1,2,3]}",
    action: "Paste compact API payloads to format or minify them.",
    result: "{\n  \"status\": \"ok\"\n}",
  }),
  tool({
    slug: "jwt-decoder",
    title: "JWT Decoder",
    shortTitle: "JWT",
    category: "Security",
    description: "Decode JWT header and payload segments locally for quick inspection.",
    component: "jwt",
    accent: "border-rose-500",
    demandTier: "core",
    keywords: ["jwt decoder", "decode jwt", "json web token", "jwt payload"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["base64-tool", "timestamp-converter", "json-formatter"],
    sample: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMifQ.signature",
    action: "Decode header and payload claims without verifying the signature.",
    result: "{\n  \"sub\": \"123\"\n}",
  }),
  tool({
    slug: "url-encoder",
    title: "URL Encoder",
    shortTitle: "URL",
    category: "Web",
    description: "Encode and decode URL components for query strings, redirects, and callbacks.",
    component: "url",
    accent: "border-lime-500",
    demandTier: "core",
    keywords: ["url encoder", "url decoder", "encodeURIComponent", "query string encoder"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["url-parser", "base64-tool", "meta-tag-generator"],
    sample: "https://example.com/callback?state=a b",
    action: "Encode values before nesting them inside query strings.",
    result: "https%3A%2F%2Fexample.com%2Fcallback%3Fstate%3Da%20b",
  }),
  tool({
    slug: "base64-tool",
    title: "Base64 Encoder Decoder",
    shortTitle: "Base64",
    category: "Data",
    description: "Encode and decode UTF-8 text to and from Base64 in the browser.",
    component: "base64",
    accent: "border-fuchsia-500",
    demandTier: "core",
    keywords: ["base64 encoder", "base64 decoder", "decode base64", "encode base64"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["jwt-decoder", "url-encoder", "hash-generator"],
    sample: "hello world",
    action: "Encode plain text or decode Base64 transport values.",
    result: "aGVsbG8gd29ybGQ=",
  }),
  tool({
    slug: "timestamp-converter",
    title: "Timestamp Converter",
    shortTitle: "Timestamp",
    category: "Time",
    description: "Convert Unix timestamps, milliseconds, and ISO strings into readable dates.",
    component: "timestamp",
    accent: "border-blue-500",
    demandTier: "core",
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "date converter"],
    guideSlug: "cron-expression-examples",
    guideTitle: "Cron expression examples and scheduling caveats",
    relatedTools: ["timezone-converter", "cron-generator", "jwt-decoder"],
    sample: "1780646400",
    action: "Paste Unix seconds, milliseconds, or an ISO string.",
    result: "ISO date, local date, Unix seconds, Unix milliseconds",
  }),
  tool({
    slug: "uuid-generator",
    title: "UUID Generator",
    shortTitle: "UUID",
    category: "Code",
    description: "Generate UUID v4 values in bulk for fixtures, traces, and test data.",
    component: "uuid",
    accent: "border-teal-500",
    demandTier: "core",
    keywords: ["uuid generator", "uuid v4", "random uuid", "guid generator"],
    guideSlug: "secure-generator-workflow",
    guideTitle: "Secure random generator workflow",
    relatedTools: ["ulid-generator", "random-token-generator", "password-generator"],
    sample: "5 UUIDs",
    action: "Generate identifiers for fixtures and local development.",
    result: "550e8400-e29b-41d4-a716-446655440000",
  }),
  tool({
    slug: "hash-generator",
    title: "Hash Generator",
    shortTitle: "Hash",
    category: "Security",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes locally.",
    component: "hash",
    accent: "border-red-500",
    demandTier: "core",
    keywords: ["hash generator", "sha256 generator", "md5 generator", "sha512 hash"],
    guideSlug: "hash-generator-security",
    guideTitle: "Hash generator security notes",
    relatedTools: ["base64-tool", "random-token-generator", "password-generator"],
    sample: "hello world",
    action: "Generate repeatable hashes for checksums and debugging.",
    result: "SHA-256: b94d27b9934d3e08...",
  }),
  tool({
    slug: "text-diff",
    title: "Text Diff",
    shortTitle: "Diff",
    category: "Text",
    description: "Compare two text blocks with line or word level differences.",
    component: "diff",
    accent: "border-emerald-600",
    demandTier: "core",
    keywords: ["text diff", "diff checker", "compare text", "word diff"],
    guideSlug: "text-diff-for-developers",
    guideTitle: "Text diff workflow for developers",
    relatedTools: ["json-formatter", "text-sort-dedupe", "word-character-counter"],
    sample: "before text / after text",
    action: "Paste two versions to see added and removed lines or words.",
    result: "- old line\n+ new line",
  }),
  tool({
    slug: "yaml-json-converter",
    title: "YAML JSON Converter",
    shortTitle: "YAML JSON",
    category: "Data",
    description: "Convert YAML to JSON and JSON to YAML for config and API workflows.",
    component: "yamlJson",
    accent: "border-yellow-500",
    demandTier: "core",
    keywords: ["yaml to json", "json to yaml", "yaml json converter", "convert yaml"],
    guideSlug: "json-yaml-csv-conversion",
    guideTitle: "JSON, YAML, and CSV conversion workflow",
    relatedTools: ["json-formatter", "csv-json-converter", "json-schema-validator"],
    sample: "name: Bob\nactive: true",
    action: "Convert configuration snippets between YAML and JSON.",
    result: "{\n  \"name\": \"Bob\"\n}",
  }),
  tool({
    slug: "sql-formatter",
    title: "SQL Formatter",
    shortTitle: "SQL",
    category: "Code",
    description: "Format SQL queries for readable reviews and debugging.",
    component: "sqlFormatter",
    accent: "border-indigo-500",
    demandTier: "core",
    keywords: ["sql formatter", "format sql", "sql beautifier", "sql minifier"],
    guideSlug: "sql-formatting-workflow",
    guideTitle: "SQL formatting workflow",
    relatedTools: ["json-formatter", "text-diff", "csv-json-converter"],
    sample: "select id,name from users where active=1 order by created_at desc",
    action: "Pretty-print compact SQL and compare query revisions.",
    result: "SELECT\n  id,\n  name\nFROM users",
  }),
  tool({
    slug: "xml-formatter",
    title: "XML Formatter",
    shortTitle: "XML",
    category: "Data",
    description: "Format and minify XML strings in the browser.",
    component: "xmlFormatter",
    accent: "border-stone-500",
    demandTier: "core",
    keywords: ["xml formatter", "xml beautifier", "xml minifier", "format xml"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["html-formatter", "json-formatter", "html-entity-converter"],
    sample: "<root><item id=\"1\">Bob</item></root>",
    action: "Beautify compact XML payloads before inspection.",
    result: "<root>\n  <item id=\"1\">Bob</item>\n</root>",
  }),
  tool({
    slug: "csv-json-converter",
    title: "CSV JSON Converter",
    shortTitle: "CSV JSON",
    category: "Data",
    description: "Convert CSV rows to JSON arrays and JSON arrays back to CSV.",
    component: "csvJson",
    accent: "border-green-500",
    demandTier: "core",
    keywords: ["csv to json", "json to csv", "csv json converter", "convert csv"],
    guideSlug: "json-yaml-csv-conversion",
    guideTitle: "JSON, YAML, and CSV conversion workflow",
    relatedTools: ["json-formatter", "yaml-json-converter", "text-sort-dedupe"],
    sample: "id,name\n1,Bob",
    action: "Convert spreadsheet exports and API fixtures.",
    result: "[{\"id\":\"1\",\"name\":\"Bob\"}]",
  }),
  tool({
    slug: "html-entity-converter",
    title: "HTML Entity Converter",
    shortTitle: "HTML Entity",
    category: "Web",
    description: "Encode and decode HTML entities for snippets, docs, and templates.",
    component: "htmlEntity",
    accent: "border-pink-500",
    demandTier: "core",
    keywords: ["html entity encoder", "html entity decoder", "escape html", "decode html entities"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["html-formatter", "xml-formatter", "url-encoder"],
    sample: "<span>Bob & Co</span>",
    action: "Escape snippets before showing HTML as text.",
    result: "&lt;span&gt;Bob &amp; Co&lt;/span&gt;",
  }),
  tool({
    slug: "color-converter",
    title: "Color Converter",
    shortTitle: "Color",
    category: "Color",
    description: "Convert HEX, RGB, and HSL colors and check WCAG contrast.",
    component: "colorConverter",
    accent: "border-purple-500",
    demandTier: "core",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "contrast checker"],
    guideSlug: "color-contrast-checking",
    guideTitle: "Color conversion and contrast checking",
    relatedTools: ["css-clamp-generator", "css-unit-converter", "favicon-generator"],
    sample: "#2563eb on #ffffff",
    action: "Convert color formats and verify readable foreground/background pairs.",
    result: "RGB 37, 99, 235 / contrast 5.17",
  }),
  tool({
    slug: "password-generator",
    title: "Password Generator",
    shortTitle: "Password",
    category: "Security",
    description: "Generate strong random passwords with configurable character sets.",
    component: "passwordGenerator",
    accent: "border-red-600",
    demandTier: "core",
    keywords: ["password generator", "strong password", "random password", "secure password generator"],
    guideSlug: "secure-generator-workflow",
    guideTitle: "Secure random generator workflow",
    relatedTools: ["random-token-generator", "uuid-generator", "hash-generator"],
    sample: "24 characters, symbols enabled",
    action: "Create local test credentials or temporary secrets.",
    result: "A strong mixed-character password",
  }),
  tool({
    slug: "qr-code-generator",
    title: "QR Code Generator",
    shortTitle: "QR Code",
    category: "Web",
    description: "Generate downloadable QR codes for URLs, text, Wi-Fi, and contact snippets.",
    component: "qrCode",
    accent: "border-neutral-600",
    demandTier: "core",
    keywords: ["qr code generator", "qr generator", "wifi qr code", "download qr code"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["url-encoder", "favicon-generator", "open-graph-preview"],
    sample: "https://www.bobob.app",
    action: "Generate a QR code image locally in the browser.",
    result: "PNG data URL",
  }),
  tool({
    slug: "random-token-generator",
    title: "Random Token Generator",
    shortTitle: "Token",
    category: "Security",
    description: "Generate secure random hex, Base64, and URL-safe tokens.",
    component: "randomToken",
    accent: "border-red-400",
    demandTier: "core",
    keywords: ["random token generator", "secure token", "hex token", "base64 token"],
    guideSlug: "secure-generator-workflow",
    guideTitle: "Secure random generator workflow",
    relatedTools: ["password-generator", "uuid-generator", "hash-generator"],
    sample: "32 bytes, URL-safe",
    action: "Create random tokens for local tests and fixtures.",
    result: "eCm1wIvDr0Jj7E7mWZgP...",
  }),
  tool({
    slug: "case-converter",
    title: "Case Converter",
    shortTitle: "Case",
    category: "Text",
    description: "Convert text between lower, upper, title, camel, pascal, snake, and kebab case.",
    component: "caseConverter",
    accent: "border-zinc-500",
    demandTier: "core",
    keywords: ["case converter", "camel case converter", "snake case converter", "kebab case"],
    guideSlug: "text-cleanup-workflow",
    guideTitle: "Text cleanup workflow",
    relatedTools: ["slug-generator", "text-sort-dedupe", "word-character-counter"],
    sample: "Bob's multi tool",
    action: "Normalize names for code, slugs, and labels.",
    result: "bobsMultiTool / bobs_multi_tool / bobs-multi-tool",
  }),
  tool({
    slug: "slug-generator",
    title: "Slug Generator",
    shortTitle: "Slug",
    category: "Text",
    description: "Create URL-safe slugs from titles, labels, and filenames.",
    component: "slugGenerator",
    accent: "border-zinc-600",
    demandTier: "growth",
    keywords: ["slug generator", "url slug", "slugify", "title to slug"],
    guideSlug: "text-cleanup-workflow",
    guideTitle: "Text cleanup workflow",
    relatedTools: ["case-converter", "url-encoder", "meta-tag-generator"],
    sample: "Bob's Multi Tool: JSON Formatter",
    action: "Convert readable titles into stable route slugs.",
    result: "bobs-multi-tool-json-formatter",
  }),
  tool({
    slug: "json-to-typescript",
    title: "JSON to TypeScript",
    shortTitle: "JSON TS",
    category: "Code",
    description: "Infer TypeScript interfaces from sample JSON objects.",
    component: "jsonToTypescript",
    accent: "border-blue-600",
    demandTier: "core",
    keywords: ["json to typescript", "json to interface", "typescript interface generator", "json types"],
    guideSlug: "json-yaml-csv-conversion",
    guideTitle: "JSON, YAML, and CSV conversion workflow",
    relatedTools: ["json-formatter", "json-schema-validator", "jsonpath-tester"],
    sample: "{\"id\":1,\"name\":\"Bob\"}",
    action: "Generate starter interfaces from example API responses.",
    result: "interface Root { id: number; name: string; }",
  }),
  tool({
    slug: "json-schema-validator",
    title: "JSON Schema Validator",
    shortTitle: "Schema",
    category: "Data",
    description: "Validate JSON values against simple JSON Schema object rules.",
    component: "jsonSchema",
    accent: "border-orange-600",
    demandTier: "core",
    keywords: ["json schema validator", "validate json schema", "json schema online", "schema checker"],
    guideSlug: "json-yaml-csv-conversion",
    guideTitle: "JSON, YAML, and CSV conversion workflow",
    relatedTools: ["json-formatter", "json-to-typescript", "jsonpath-tester"],
    sample: "{\"type\":\"object\",\"required\":[\"id\"]}",
    action: "Check required fields and primitive types in test payloads.",
    result: "Valid / Invalid with issues",
  }),
  tool({
    slug: "jsonpath-tester",
    title: "JSONPath Tester",
    shortTitle: "JSONPath",
    category: "Data",
    description: "Evaluate simple JSONPath-style selectors against JSON payloads.",
    component: "jsonPath",
    accent: "border-orange-400",
    demandTier: "growth",
    keywords: ["jsonpath tester", "json path evaluator", "json query", "jsonpath online"],
    guideSlug: "json-yaml-csv-conversion",
    guideTitle: "JSON, YAML, and CSV conversion workflow",
    relatedTools: ["json-formatter", "json-to-typescript", "json-schema-validator"],
    sample: "$.items[0].name",
    action: "Find nested values in API responses.",
    result: "\"Bob\"",
  }),
  tool({
    slug: "html-formatter",
    title: "HTML Formatter",
    shortTitle: "HTML",
    category: "Web",
    description: "Beautify compact HTML snippets for templates and documentation.",
    component: "htmlFormatter",
    accent: "border-orange-700",
    demandTier: "core",
    keywords: ["html formatter", "html beautifier", "format html", "html pretty print"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["html-entity-converter", "xml-formatter", "css-formatter"],
    sample: "<div><span>Bob</span></div>",
    action: "Pretty-print markup before reviewing or documenting it.",
    result: "<div>\n  <span>Bob</span>\n</div>",
  }),
  tool({
    slug: "css-formatter",
    title: "CSS Formatter",
    shortTitle: "CSS",
    category: "Code",
    description: "Beautify compact CSS rules for review and debugging.",
    component: "cssFormatter",
    accent: "border-blue-700",
    demandTier: "core",
    keywords: ["css formatter", "css beautifier", "format css", "css pretty print"],
    guideSlug: "css-utility-workflow",
    guideTitle: "CSS utility workflow",
    relatedTools: ["css-minifier", "css-unit-converter", "css-clamp-generator"],
    sample: ".card{display:flex;color:#111}",
    action: "Format CSS declarations and blocks.",
    result: ".card {\n  display: flex;\n  color: #111;\n}",
  }),
  tool({
    slug: "css-minifier",
    title: "CSS Minifier",
    shortTitle: "CSS Min",
    category: "Code",
    description: "Minify CSS by removing comments and unnecessary whitespace.",
    component: "cssMinifier",
    accent: "border-blue-500",
    demandTier: "growth",
    keywords: ["css minifier", "minify css", "compress css", "css optimizer"],
    guideSlug: "css-utility-workflow",
    guideTitle: "CSS utility workflow",
    relatedTools: ["css-formatter", "javascript-minifier", "html-formatter"],
    sample: ".card { color: #111; }",
    action: "Compress small snippets for quick experiments.",
    result: ".card{color:#111}",
  }),
  tool({
    slug: "javascript-formatter",
    title: "JavaScript Formatter",
    shortTitle: "JS",
    category: "Code",
    description: "Format small JavaScript snippets for readable inspection.",
    component: "javascriptFormatter",
    accent: "border-yellow-600",
    demandTier: "core",
    keywords: ["javascript formatter", "js formatter", "format javascript", "javascript beautifier"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["javascript-minifier", "json-formatter", "regex-tester"],
    sample: "function hi(){console.log('bob');}",
    action: "Beautify short scripts and bookmarklet snippets.",
    result: "function hi() {\n  console.log('bob');\n}",
  }),
  tool({
    slug: "javascript-minifier",
    title: "JavaScript Minifier",
    shortTitle: "JS Min",
    category: "Code",
    description: "Minify small JavaScript snippets by stripping comments and whitespace.",
    component: "javascriptMinifier",
    accent: "border-yellow-500",
    demandTier: "growth",
    keywords: ["javascript minifier", "js minifier", "minify javascript", "compress javascript"],
    guideSlug: "developer-utility-workflow",
    guideTitle: "A practical workflow for browser-based developer utilities",
    relatedTools: ["javascript-formatter", "css-minifier", "html-formatter"],
    sample: "function hi() { console.log('bob'); }",
    action: "Compress small snippets for quick copy-paste use.",
    result: "function hi(){console.log('bob');}",
  }),
  tool({
    slug: "markdown-previewer",
    title: "Markdown Previewer",
    shortTitle: "Markdown",
    category: "Text",
    description: "Preview headings, lists, code blocks, and links from Markdown text.",
    component: "markdownPreview",
    accent: "border-slate-500",
    demandTier: "growth",
    keywords: ["markdown previewer", "markdown editor", "preview markdown", "markdown online"],
    guideSlug: "text-cleanup-workflow",
    guideTitle: "Text cleanup workflow",
    relatedTools: ["word-character-counter", "html-formatter", "text-diff"],
    sample: "# Title\n- Item",
    action: "Preview docs snippets before pasting them elsewhere.",
    result: "Rendered heading and list",
  }),
  tool({
    slug: "text-sort-dedupe",
    title: "Text Sort and Dedupe",
    shortTitle: "Sort",
    category: "Text",
    description: "Sort lines, remove duplicates, trim blanks, and normalize pasted lists.",
    component: "textSortDedupe",
    accent: "border-zinc-400",
    demandTier: "core",
    keywords: ["sort lines", "remove duplicate lines", "dedupe text", "text sorter"],
    guideSlug: "text-cleanup-workflow",
    guideTitle: "Text cleanup workflow",
    relatedTools: ["case-converter", "word-character-counter", "text-diff"],
    sample: "beta\nalpha\nbeta",
    action: "Clean pasted IDs, words, and newline-separated data.",
    result: "alpha\nbeta",
  }),
  tool({
    slug: "word-character-counter",
    title: "Word Character Counter",
    shortTitle: "Counter",
    category: "Text",
    description: "Count characters, words, lines, bytes, and estimated reading time.",
    component: "wordCounter",
    accent: "border-zinc-500",
    demandTier: "core",
    keywords: ["word counter", "character counter", "line counter", "text counter"],
    guideSlug: "text-cleanup-workflow",
    guideTitle: "Text cleanup workflow",
    relatedTools: ["text-sort-dedupe", "lorem-ipsum-generator", "markdown-previewer"],
    sample: "Bob's Multi Tool",
    action: "Measure copy, textarea limits, and docs snippets.",
    result: "3 words, 16 characters",
  }),
  tool({
    slug: "url-parser",
    title: "URL Parser",
    shortTitle: "URL Parse",
    category: "Web",
    description: "Break URLs into protocol, host, pathname, query params, hash, and origin.",
    component: "urlParser",
    accent: "border-lime-600",
    demandTier: "core",
    keywords: ["url parser", "parse url", "query string parser", "url components"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["url-encoder", "http-status-checker", "open-graph-preview"],
    sample: "https://example.com/tools?q=json#top",
    action: "Inspect redirects, callback URLs, and query parameters.",
    result: "protocol, hostname, pathname, searchParams",
  }),
  tool({
    slug: "mime-type-lookup",
    title: "MIME Type Lookup",
    shortTitle: "MIME",
    category: "Web",
    description: "Look up common MIME types by file extension or content type.",
    component: "mimeLookup",
    accent: "border-cyan-600",
    demandTier: "growth",
    keywords: ["mime type lookup", "content type lookup", "file mime type", "mime type checker"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["http-status-checker", "url-parser", "html-formatter"],
    sample: ".json",
    action: "Check headers and upload content types quickly.",
    result: "application/json",
  }),
  tool({
    slug: "ulid-generator",
    title: "ULID Generator",
    shortTitle: "ULID",
    category: "Code",
    description: "Generate sortable ULID identifiers for logs, fixtures, and test records.",
    component: "ulid",
    accent: "border-teal-600",
    demandTier: "growth",
    keywords: ["ulid generator", "sortable id generator", "unique id generator", "ulid online"],
    guideSlug: "secure-generator-workflow",
    guideTitle: "Secure random generator workflow",
    relatedTools: ["uuid-generator", "random-token-generator", "timestamp-converter"],
    sample: "5 ULIDs",
    action: "Generate timestamp-sortable IDs locally.",
    result: "01JX2M8Q9VG6K7...",
  }),
  tool({
    slug: "robots-txt-generator",
    title: "Robots.txt Generator",
    shortTitle: "Robots",
    category: "SEO",
    description: "Generate robots.txt rules with sitemap and crawl controls.",
    component: "robotsGenerator",
    accent: "border-violet-600",
    demandTier: "growth",
    keywords: ["robots.txt generator", "robots txt", "generate robots.txt", "seo robots file"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["sitemap-generator", "meta-tag-generator", "open-graph-preview"],
    sample: "Allow all with sitemap",
    action: "Create simple crawl directives for a public site.",
    result: "User-agent: *\nAllow: /\nSitemap: ...",
  }),
  tool({
    slug: "sitemap-generator",
    title: "Sitemap Generator",
    shortTitle: "Sitemap",
    category: "SEO",
    description: "Generate XML sitemap entries from a list of public URLs.",
    component: "sitemapGenerator",
    accent: "border-violet-500",
    demandTier: "growth",
    keywords: ["sitemap generator", "xml sitemap", "generate sitemap", "seo sitemap"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["robots-txt-generator", "meta-tag-generator", "url-parser"],
    sample: "https://www.bobob.app/\nhttps://www.bobob.app/tools/json-formatter",
    action: "Turn a URL list into a valid XML sitemap snippet.",
    result: "<urlset>...</urlset>",
  }),
  tool({
    slug: "open-graph-preview",
    title: "Open Graph Preview",
    shortTitle: "OG Preview",
    category: "SEO",
    description: "Build a visual preview for Open Graph title, description, URL, and image fields.",
    component: "openGraphPreview",
    accent: "border-violet-400",
    demandTier: "core",
    keywords: ["open graph preview", "og preview", "social preview", "meta preview"],
    guideSlug: "seo-meta-tags",
    guideTitle: "SEO meta tags that are worth generating",
    relatedTools: ["meta-tag-generator", "favicon-generator", "url-parser"],
    sample: "Title, description, image URL",
    action: "Preview how a shared page card might read.",
    result: "Card preview plus meta tags",
  }),
  tool({
    slug: "favicon-generator",
    title: "Favicon Generator",
    shortTitle: "Favicon",
    category: "SEO",
    description: "Generate a simple SVG favicon and HTML link tags from text and colors.",
    component: "faviconGenerator",
    accent: "border-violet-700",
    demandTier: "growth",
    keywords: ["favicon generator", "svg favicon", "generate favicon", "favicon html"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["color-converter", "open-graph-preview", "meta-tag-generator"],
    sample: "B on #18181b",
    action: "Create a lightweight SVG favicon for prototypes.",
    result: "<link rel=\"icon\" href=\"data:image/svg+xml,...\" />",
  }),
  tool({
    slug: "http-status-checker",
    title: "HTTP Status Checker",
    shortTitle: "HTTP",
    category: "Network",
    description: "Check the HTTP status, final URL, and response headers for public URLs.",
    component: "httpStatus",
    accent: "border-cyan-700",
    demandTier: "core",
    privacyMode: "server",
    requiresServer: true,
    keywords: ["http status checker", "status code checker", "url status checker", "redirect checker"],
    guideSlug: "network-debugging-tools",
    guideTitle: "Network debugging tools workflow",
    relatedTools: ["dns-lookup", "url-parser", "open-graph-preview"],
    sample: "https://www.bobob.app",
    action: "Check public URL status and redirect behavior.",
    result: "200 OK / final URL / content-type",
  }),
  tool({
    slug: "dns-lookup",
    title: "DNS Lookup",
    shortTitle: "DNS",
    category: "Network",
    description: "Look up public DNS records for A, AAAA, CNAME, MX, TXT, and NS.",
    component: "dnsLookup",
    accent: "border-cyan-500",
    demandTier: "core",
    privacyMode: "server",
    requiresServer: true,
    keywords: ["dns lookup", "dns checker", "mx lookup", "txt lookup"],
    guideSlug: "network-debugging-tools",
    guideTitle: "Network debugging tools workflow",
    relatedTools: ["http-status-checker", "url-parser", "mime-type-lookup"],
    sample: "bobob.app, A",
    action: "Inspect public DNS records while debugging domains.",
    result: "A records or resolver error",
  }),
  tool({
    slug: "user-agent-parser",
    title: "User-Agent Parser",
    shortTitle: "UA Parser",
    category: "Web",
    description: "Parse common browser, OS, rendering engine, and device hints from a user-agent string.",
    component: "userAgentParser",
    accent: "border-cyan-400",
    demandTier: "growth",
    keywords: ["user agent parser", "parse user agent", "browser detector", "ua parser"],
    guideSlug: "web-seo-utilities",
    guideTitle: "Practical web and SEO utilities",
    relatedTools: ["http-status-checker", "iframe-viewer", "url-parser"],
    sample: "Mozilla/5.0 ... Chrome/124.0 Safari/537.36",
    action: "Inspect browser and platform hints from logs.",
    result: "Chrome / macOS / desktop",
  }),
  tool({
    slug: "timezone-converter",
    title: "Timezone Converter",
    shortTitle: "Timezone",
    category: "Time",
    description: "Compare a date and time across common IANA time zones.",
    component: "timezoneConverter",
    accent: "border-blue-400",
    demandTier: "core",
    keywords: ["timezone converter", "time zone converter", "utc converter", "world time converter"],
    guideSlug: "cron-expression-examples",
    guideTitle: "Cron expression examples and scheduling caveats",
    relatedTools: ["timestamp-converter", "cron-generator", "jwt-decoder"],
    sample: "2026-06-05T09:00:00Z",
    action: "Check scheduling and log times across regions.",
    result: "UTC, Seoul, Tokyo, New York, London",
  }),
  tool({
    slug: "css-unit-converter",
    title: "CSS Unit Converter",
    shortTitle: "CSS Unit",
    category: "Color",
    description: "Convert px, rem, em, and percent values for CSS layout calculations.",
    component: "cssUnitConverter",
    accent: "border-purple-600",
    demandTier: "growth",
    keywords: ["css unit converter", "px to rem", "rem to px", "em converter"],
    guideSlug: "css-utility-workflow",
    guideTitle: "CSS utility workflow",
    relatedTools: ["css-clamp-generator", "color-converter", "css-formatter"],
    sample: "16px at 16px root",
    action: "Convert spacing and typography values between common CSS units.",
    result: "1rem / 1em / 100%",
  }),
  tool({
    slug: "css-clamp-generator",
    title: "CSS Clamp Generator",
    shortTitle: "Clamp",
    category: "Color",
    description: "Generate CSS clamp() expressions for responsive font sizes and spacing.",
    component: "cssClampGenerator",
    accent: "border-purple-400",
    demandTier: "growth",
    keywords: ["css clamp generator", "fluid typography", "responsive font size", "clamp calculator"],
    guideSlug: "css-utility-workflow",
    guideTitle: "CSS utility workflow",
    relatedTools: ["css-unit-converter", "color-converter", "css-formatter"],
    sample: "16px at 360px, 32px at 1200px",
    action: "Generate fluid CSS values with min and max bounds.",
    result: "clamp(1rem, 0.5714rem + 1.9048vw, 2rem)",
  }),
];

export const toolCategories = Array.from(new Set(tools.map((tool) => tool.category)));

export function getToolBySlug(slug: string) {
  return tools.find((toolItem) => toolItem.slug === slug);
}

export function getRelatedTools(slugs: string[]) {
  return slugs.map((slug) => getToolBySlug(slug)).filter((toolItem): toolItem is ToolDefinition => Boolean(toolItem));
}

export function getToolSearchText(tool: ToolDefinition) {
  return [
    tool.title,
    tool.shortTitle,
    tool.slug,
    tool.category,
    tool.description,
    tool.contentCluster,
    tool.demandTier,
    tool.monetizationTier,
    ...tool.searchIntents,
    ...tool.aliases,
    ...tool.useCases,
    ...tool.inputExamples,
    ...tool.seo.keywords,
    tool.seo.title,
    tool.seo.description,
    ...tool.examples.flatMap((example) => [example.label, example.value, example.note]),
    ...tool.faqs.flatMap((faq) => [faq.question, faq.answer]),
    ...tool.guides.map((guideLink) => guideLink.title),
  ].join(" ");
}

function normalizeSearch(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9가-힣一-龥ぁ-んァ-ン]+/g, " ").trim();
}

export function scoreToolSearch(tool: ToolDefinition, query: string) {
  const normalizedQuery = normalizeSearch(query);
  if (!normalizedQuery) return demandWeight[tool.demandTier];

  const title = normalizeSearch(tool.title);
  const shortTitle = normalizeSearch(tool.shortTitle);
  const slug = normalizeSearch(tool.slug.replace(/-/g, " "));
  const aliases = tool.aliases.map(normalizeSearch);
  const keywords = tool.seo.keywords.map(normalizeSearch);
  const intents = tool.searchIntents.map(normalizeSearch);
  const searchText = normalizeSearch(getToolSearchText(tool));
  const terms = normalizedQuery.split(/\s+/).filter(Boolean);

  let score = demandWeight[tool.demandTier];
  if (title === normalizedQuery || shortTitle === normalizedQuery || slug === normalizedQuery) score += 120;
  if (title.startsWith(normalizedQuery) || slug.startsWith(normalizedQuery)) score += 70;
  if (aliases.some((alias) => alias === normalizedQuery)) score += 90;
  if (aliases.some((alias) => alias.includes(normalizedQuery))) score += 55;
  if (keywords.some((keyword) => keyword === normalizedQuery) || intents.some((intent) => intent === normalizedQuery)) score += 65;
  if (keywords.some((keyword) => keyword.includes(normalizedQuery)) || intents.some((intent) => intent.includes(normalizedQuery))) score += 35;

  for (const term of terms) {
    if (title.includes(term) || slug.includes(term)) score += 24;
    if (aliases.some((alias) => alias.includes(term))) score += 18;
    if (keywords.some((keyword) => keyword.includes(term)) || intents.some((intent) => intent.includes(term))) score += 14;
    if (searchText.includes(term)) score += 5;
  }

  return score;
}

export function searchTools(query: string, source: ToolDefinition[] = tools) {
  const normalizedQuery = normalizeSearch(query);
  if (!normalizedQuery) return source;
  return source
    .map((toolItem) => ({ tool: toolItem, score: scoreToolSearch(toolItem, normalizedQuery) }))
    .filter((item) => item.score > demandWeight[item.tool.demandTier])
    .sort((a, b) => b.score - a.score || a.tool.title.localeCompare(b.tool.title))
    .map((item) => item.tool);
}
