import type { Locale } from "@/features/i18n/config";
import type { ToolDefinition } from "./types";

type LocalizedText = Record<Locale, string>;

export interface WorkflowStep {
  toolSlug: string;
  reason: LocalizedText;
}

export interface WorkflowRecipe {
  slug: string;
  title: LocalizedText;
  description: LocalizedText;
  searchIntents: string[];
  steps: WorkflowStep[];
}

export interface LocalizedWorkflowStep {
  tool: ToolDefinition;
  reason: string;
}

export interface LocalizedWorkflowRecipe {
  slug: string;
  title: string;
  description: string;
  searchIntents: string[];
  steps: LocalizedWorkflowStep[];
}

const text = (values: LocalizedText, locale: Locale) => values[locale] ?? values.en;

const localized = (values: LocalizedText) => values;

export const workflowRecipes: WorkflowRecipe[] = [
  {
    slug: "format-api-response",
    title: localized({
      en: "Format an API response",
      ko: "API 응답 정리",
      ja: "APIレスポンスを整える",
      "zh-CN": "整理 API 响应",
      "zh-TW": "整理 API 回應",
      es: "Formatear una respuesta API",
      "pt-BR": "Formatar uma resposta de API",
      de: "API-Antwort formatieren",
      fr: "Formater une reponse API",
      hi: "API response को व्यवस्थित करें",
      id: "Rapikan respons API",
      vi: "Định dạng phản hồi API",
      th: "จัดรูปแบบ response API",
      ar: "تنسيق استجابة API",
    }),
    description: localized({
      en: "Clean a pasted JSON payload, inspect paths, then create types or schema checks.",
      ko: "붙여 넣은 JSON을 정리하고 경로를 확인한 뒤 타입이나 스키마 검증으로 이어갑니다.",
      ja: "貼り付けたJSONを整形し、パスを確認して型やスキーマ確認へ進みます。",
      "zh-CN": "整理粘贴的 JSON，检查路径，再生成类型或做 schema 校验。",
      "zh-TW": "整理貼上的 JSON，檢查路徑，再產生型別或做 schema 驗證。",
      es: "Limpia JSON pegado, revisa rutas y sigue con tipos o validacion de esquema.",
      "pt-BR": "Limpe JSON colado, revise caminhos e siga para tipos ou schema.",
      de: "Bereinige eingefuegtes JSON, pruefe Pfade und erstelle Typen oder Schema-Checks.",
      fr: "Nettoyez un JSON colle, verifiez les chemins, puis creez types ou controles schema.",
      hi: "चिपकाए गए JSON को साफ करें, paths देखें, फिर types या schema जांच बनाएं.",
      id: "Bersihkan JSON tempel, periksa path, lalu buat tipe atau cek schema.",
      vi: "Làm sạch JSON đã dán, kiểm tra path rồi tạo type hoặc kiểm tra schema.",
      th: "จัด JSON ที่วาง ตรวจ path แล้วต่อด้วย type หรือ schema check",
      ar: "نظف JSON الملصق وافحص المسارات ثم أنشئ الانواع أو تحقق من schema.",
    }),
    searchIntents: ["api response formatter", "json response viewer", "json to typescript workflow", "json schema check"],
    steps: [
      {
        toolSlug: "json-formatter",
        reason: localized({
          en: "Validate and format the payload before copying it.",
          ko: "복사 전에 페이로드를 검증하고 보기 좋게 정리합니다.",
          ja: "コピー前にペイロードを検証して整形します。",
          "zh-CN": "复制前先验证并格式化 payload。",
          "zh-TW": "複製前先驗證並格式化 payload。",
          es: "Valida y formatea el payload antes de copiarlo.",
          "pt-BR": "Valide e formate o payload antes de copiar.",
          de: "Validiere und formatiere den Payload vor dem Kopieren.",
          fr: "Validez et formatez le payload avant copie.",
          hi: "कॉपी से पहले payload को validate और format करें.",
          id: "Validasi dan format payload sebelum disalin.",
          vi: "Xác thực và định dạng payload trước khi sao chép.",
          th: "ตรวจและจัด payload ก่อนคัดลอก",
          ar: "تحقق من payload ونسقه قبل النسخ.",
        }),
      },
      {
        toolSlug: "jsonpath-tester",
        reason: localized({
          en: "Pull the exact field path needed by code or docs.",
          ko: "코드나 문서에 필요한 정확한 필드 경로를 뽑습니다.",
          ja: "コードや文書に必要な正確なフィールドパスを取り出します。",
          "zh-CN": "取出代码或文档需要的精确字段路径。",
          "zh-TW": "取出程式或文件需要的精確欄位路徑。",
          es: "Extrae la ruta exacta del campo que necesita el codigo o la documentacion.",
          "pt-BR": "Extraia o caminho exato do campo usado no codigo ou docs.",
          de: "Extrahiere den genauen Feldpfad fuer Code oder Dokumentation.",
          fr: "Recuperez le chemin exact du champ pour le code ou la documentation.",
          hi: "code या docs के लिए सही field path निकालें.",
          id: "Ambil path field yang tepat untuk kode atau dokumentasi.",
          vi: "Lấy đúng path trường cần cho code hoặc tài liệu.",
          th: "ดึง path ของ field ที่ code หรือเอกสารต้องใช้",
          ar: "استخرج مسار الحقل الدقيق للكود أو المستندات.",
        }),
      },
      {
        toolSlug: "json-to-typescript",
        reason: localized({
          en: "Turn the sample shape into a starter interface.",
          ko: "샘플 구조를 TypeScript 인터페이스 초안으로 바꿉니다.",
          ja: "サンプル構造をTypeScript interfaceの下書きに変えます。",
          "zh-CN": "把样例结构转换成 TypeScript interface 草稿。",
          "zh-TW": "把範例結構轉成 TypeScript interface 草稿。",
          es: "Convierte la forma de ejemplo en una interfaz inicial.",
          "pt-BR": "Converta a estrutura de exemplo em uma interface inicial.",
          de: "Wandle die Beispielstruktur in ein erstes Interface um.",
          fr: "Transformez la structure d'exemple en interface de depart.",
          hi: "sample shape को शुरुआती interface में बदलें.",
          id: "Ubah bentuk contoh menjadi interface awal.",
          vi: "Chuyển cấu trúc mẫu thành interface ban đầu.",
          th: "เปลี่ยนโครงสร้างตัวอย่างเป็น interface เริ่มต้น",
          ar: "حول شكل العينة إلى interface مبدئي.",
        }),
      },
    ],
  },
  {
    slug: "extract-json-field",
    title: localized({
      en: "Extract a JSON field",
      ko: "JSON 필드 추출",
      ja: "JSONフィールドを抽出",
      "zh-CN": "提取 JSON 字段",
      "zh-TW": "擷取 JSON 欄位",
      es: "Extraer un campo JSON",
      "pt-BR": "Extrair campo JSON",
      de: "JSON-Feld extrahieren",
      fr: "Extraire un champ JSON",
      hi: "JSON field निकालें",
      id: "Ekstrak field JSON",
      vi: "Trích xuất trường JSON",
      th: "ดึง field จาก JSON",
      ar: "استخراج حقل JSON",
    }),
    description: localized({
      en: "Format the payload, test a path with wildcards or recursive keys, then keep the shape for code.",
      ko: "payload를 정리하고 wildcard나 recursive key 경로를 테스트한 뒤 코드에 쓸 구조를 남깁니다.",
      ja: "payloadを整形し、wildcardやrecursive keyのパスを試して、コードで使う形を残します。",
      "zh-CN": "格式化 payload，测试 wildcard 或递归键路径，再保留给代码使用的结构。",
      "zh-TW": "格式化 payload，測試 wildcard 或遞迴鍵路徑，再保留給程式使用的結構。",
      es: "Formatea el payload, prueba una ruta con wildcard o claves recursivas y conserva la forma para codigo.",
      "pt-BR": "Formate o payload, teste um caminho com wildcard ou chaves recursivas e mantenha a estrutura para codigo.",
      de: "Formatiere den Payload, teste Pfade mit Wildcards oder rekursiven Keys und behalte die Struktur fuer Code.",
      fr: "Formatez le payload, testez un chemin avec wildcard ou cles recursives, puis gardez la forme pour le code.",
      hi: "payload format करें, wildcard या recursive key path जांचें, फिर code के लिए shape रखें.",
      id: "Format payload, uji path wildcard atau key rekursif, lalu simpan bentuk untuk kode.",
      vi: "Định dạng payload, thử path wildcard hoặc khóa đệ quy rồi giữ cấu trúc cho code.",
      th: "จัดรูปแบบ payload ทดสอบ path แบบ wildcard หรือ key recursive แล้วเก็บโครงสร้างไว้ใช้กับ code",
      ar: "نسق payload واختبر مسارا مع wildcard أو مفاتيح recursive ثم احتفظ بالشكل للكود.",
    }),
    searchIntents: ["json field extractor", "json path extractor", "extract json value", "jsonpath wildcard", "recursive jsonpath"],
    steps: [
      {
        toolSlug: "json-formatter",
        reason: localized({
          en: "Format and validate the pasted response before selecting fields.",
          ko: "필드를 고르기 전에 붙여 넣은 응답을 정리하고 검증합니다.",
          ja: "フィールド選択前に貼り付けたレスポンスを整形して検証します。",
          "zh-CN": "选择字段前先格式化并验证粘贴的响应。",
          "zh-TW": "選擇欄位前先格式化並驗證貼上的回應。",
          es: "Formatea y valida la respuesta pegada antes de elegir campos.",
          "pt-BR": "Formate e valide a resposta colada antes de escolher campos.",
          de: "Formatiere und validiere die eingefuegte Antwort vor der Feldauswahl.",
          fr: "Formatez et validez la reponse collee avant de choisir les champs.",
          hi: "field चुनने से पहले pasted response format और validate करें.",
          id: "Format dan validasi respons yang ditempel sebelum memilih field.",
          vi: "Định dạng và xác thực phản hồi đã dán trước khi chọn trường.",
          th: "จัดรูปแบบและตรวจ response ที่วางก่อนเลือก field",
          ar: "نسق الاستجابة الملصقة وتحقق منها قبل اختيار الحقول.",
        }),
      },
      {
        toolSlug: "jsonpath-tester",
        reason: localized({
          en: "Test dot paths, bracket keys, wildcards, and recursive key searches.",
          ko: "dot path, bracket key, wildcard, recursive key 검색을 테스트합니다.",
          ja: "dot path、bracket key、wildcard、recursive key検索を試します。",
          "zh-CN": "测试 dot path、bracket key、wildcard 和递归键搜索。",
          "zh-TW": "測試 dot path、bracket key、wildcard 與遞迴鍵搜尋。",
          es: "Prueba dot paths, claves con brackets, wildcards y busquedas recursivas.",
          "pt-BR": "Teste dot paths, chaves com brackets, wildcards e buscas recursivas.",
          de: "Teste Dot-Pfade, Bracket-Keys, Wildcards und rekursive Key-Suchen.",
          fr: "Testez dot paths, cles bracket, wildcards et recherches recursives.",
          hi: "dot path, bracket key, wildcard और recursive key search जांचें.",
          id: "Uji dot path, key bracket, wildcard, dan pencarian key rekursif.",
          vi: "Thử dot path, khóa bracket, wildcard và tìm khóa đệ quy.",
          th: "ทดสอบ dot path, key แบบ bracket, wildcard และการค้น key แบบ recursive",
          ar: "اختبر dot path ومفاتيح bracket وwildcard والبحث recursive.",
        }),
      },
      {
        toolSlug: "json-to-typescript",
        reason: localized({
          en: "Create a starter type once the field shape is clear.",
          ko: "필드 구조가 명확해지면 TypeScript 타입 초안을 만듭니다.",
          ja: "フィールド構造が明確になったらTypeScript型の下書きを作ります。",
          "zh-CN": "字段结构明确后生成 TypeScript 类型草稿。",
          "zh-TW": "欄位結構明確後產生 TypeScript 型別草稿。",
          es: "Crea un tipo inicial cuando la forma del campo este clara.",
          "pt-BR": "Crie um tipo inicial quando a estrutura do campo estiver clara.",
          de: "Erstelle einen Starttyp, sobald die Feldstruktur klar ist.",
          fr: "Creez un type de depart une fois la forme du champ claire.",
          hi: "field shape साफ होने पर starter type बनाएं.",
          id: "Buat tipe awal setelah bentuk field jelas.",
          vi: "Tạo type ban đầu khi cấu trúc trường đã rõ.",
          th: "สร้าง type เริ่มต้นเมื่อโครงสร้าง field ชัดเจน",
          ar: "أنشئ نوعا مبدئيا عندما يصبح شكل الحقل واضحا.",
        }),
      },
    ],
  },
  {
    slug: "decode-api-token",
    title: localized({
      en: "Decode an API token",
      ko: "API 토큰 확인",
      ja: "APIトークンを確認",
      "zh-CN": "解读 API token",
      "zh-TW": "解讀 API token",
      es: "Decodificar un token API",
      "pt-BR": "Decodificar token de API",
      de: "API-Token pruefen",
      fr: "Decoder un token API",
      hi: "API token जांचें",
      id: "Periksa token API",
      vi: "Giải mã token API",
      th: "ตรวจ token API",
      ar: "فك ترميز رمز API",
    }),
    description: localized({
      en: "Inspect JWT claims, check time fields, and compare encoded segments safely.",
      ko: "JWT 클레임과 시간 필드를 확인하고 인코딩된 세그먼트를 안전하게 비교합니다.",
      ja: "JWT claimと時刻フィールドを確認し、エンコード済みセグメントを安全に比較します。",
      "zh-CN": "检查 JWT claim 和时间字段，并安全比较编码片段。",
      "zh-TW": "檢查 JWT claim 和時間欄位，並安全比較編碼片段。",
      es: "Revisa claims JWT, campos de tiempo y segmentos codificados con cuidado.",
      "pt-BR": "Revise claims JWT, campos de tempo e segmentos codificados com cuidado.",
      de: "Pruefe JWT-Claims, Zeitfelder und codierte Segmente sicher.",
      fr: "Inspectez les claims JWT, les champs de temps et les segments encodes.",
      hi: "JWT claims, time fields और encoded segments को सावधानी से देखें.",
      id: "Periksa claim JWT, field waktu, dan segmen terkode dengan aman.",
      vi: "Kiểm tra claim JWT, trường thời gian và đoạn mã hóa an toàn.",
      th: "ตรวจ claim JWT เวลา และ segment ที่ encode อย่างปลอดภัย",
      ar: "افحص claims في JWT وحقول الوقت والمقاطع المشفرة بأمان.",
    }),
    searchIntents: ["jwt exp checker", "api token decoder", "base64url jwt payload", "token expiry debug"],
    steps: [
      {
        toolSlug: "jwt-decoder",
        reason: localized({
          en: "Read header and payload without sending the token to a verifier.",
          ko: "토큰을 검증 서버로 보내지 않고 header와 payload를 읽습니다.",
          ja: "検証サーバーに送らずheaderとpayloadを読みます。",
          "zh-CN": "不发送到验证器，直接读取 header 和 payload。",
          "zh-TW": "不送到驗證器，直接讀取 header 與 payload。",
          es: "Lee header y payload sin enviar el token a un verificador.",
          "pt-BR": "Leia header e payload sem enviar o token a um verificador.",
          de: "Lies Header und Payload, ohne den Token an einen Verifier zu senden.",
          fr: "Lisez header et payload sans envoyer le token a un verificateur.",
          hi: "token verifier को भेजे बिना header और payload पढ़ें.",
          id: "Baca header dan payload tanpa mengirim token ke verifier.",
          vi: "Đọc header và payload mà không gửi token tới trình xác minh.",
          th: "อ่าน header และ payload โดยไม่ส่ง token ไป verifier",
          ar: "اقرأ header وpayload دون إرسال الرمز إلى مدقق.",
        }),
      },
      {
        toolSlug: "timestamp-converter",
        reason: localized({
          en: "Convert exp, iat, and nbf values into readable dates.",
          ko: "exp, iat, nbf 값을 읽기 쉬운 날짜로 바꿉니다.",
          ja: "exp、iat、nbfを読みやすい日時に変換します。",
          "zh-CN": "把 exp、iat、nbf 转成可读日期。",
          "zh-TW": "把 exp、iat、nbf 轉成可讀日期。",
          es: "Convierte exp, iat y nbf en fechas legibles.",
          "pt-BR": "Converta exp, iat e nbf em datas legiveis.",
          de: "Wandle exp, iat und nbf in lesbare Daten um.",
          fr: "Convertissez exp, iat et nbf en dates lisibles.",
          hi: "exp, iat और nbf को पढ़ने योग्य dates में बदलें.",
          id: "Ubah exp, iat, dan nbf menjadi tanggal yang mudah dibaca.",
          vi: "Chuyển exp, iat và nbf thành ngày dễ đọc.",
          th: "แปลง exp, iat, nbf เป็นวันที่อ่านง่าย",
          ar: "حول exp وiat وnbf إلى تواريخ مفهومة.",
        }),
      },
      {
        toolSlug: "base64-tool",
        reason: localized({
          en: "Compare Base64URL segments and padding issues.",
          ko: "Base64URL 세그먼트와 padding 문제를 비교합니다.",
          ja: "Base64URLセグメントとpadding問題を比較します。",
          "zh-CN": "比较 Base64URL 片段和 padding 问题。",
          "zh-TW": "比較 Base64URL 片段與 padding 問題。",
          es: "Compara segmentos Base64URL y problemas de padding.",
          "pt-BR": "Compare segmentos Base64URL e problemas de padding.",
          de: "Vergleiche Base64URL-Segmente und Padding-Probleme.",
          fr: "Comparez les segments Base64URL et les problemes de padding.",
          hi: "Base64URL segments और padding issues की तुलना करें.",
          id: "Bandingkan segmen Base64URL dan masalah padding.",
          vi: "So sánh segment Base64URL và lỗi padding.",
          th: "เทียบ segment Base64URL และปัญหา padding",
          ar: "قارن مقاطع Base64URL ومشكلات padding.",
        }),
      },
    ],
  },
  {
    slug: "debug-redirect",
    title: localized({
      en: "Debug a redirect",
      ko: "리다이렉트 디버그",
      ja: "リダイレクトを調査",
      "zh-CN": "调试重定向",
      "zh-TW": "除錯重新導向",
      es: "Depurar una redireccion",
      "pt-BR": "Depurar redirecionamento",
      de: "Redirect debuggen",
      fr: "Deboguer une redirection",
      hi: "redirect जांचें",
      id: "Debug redirect",
      vi: "Gỡ lỗi redirect",
      th: "debug redirect",
      ar: "تصحيح redirect",
    }),
    description: localized({
      en: "Check status, final URL, DNS target, and social preview signals in one path.",
      ko: "status, 최종 URL, DNS 대상, social preview 신호를 한 흐름에서 확인합니다.",
      ja: "status、最終URL、DNS先、social previewの信号を一つの流れで確認します。",
      "zh-CN": "一次检查 status、最终 URL、DNS 目标和社交预览信号。",
      "zh-TW": "一次檢查 status、最終 URL、DNS 目標與社群預覽訊號。",
      es: "Revisa status, URL final, destino DNS y senales de vista social.",
      "pt-BR": "Verifique status, URL final, destino DNS e sinais de preview social.",
      de: "Pruefe Status, finale URL, DNS-Ziel und Social-Preview-Signale.",
      fr: "Verifiez status, URL finale, cible DNS et signaux de preview social.",
      hi: "status, final URL, DNS target और social preview signal साथ देखें.",
      id: "Cek status, URL akhir, target DNS, dan sinyal preview sosial.",
      vi: "Kiểm tra status, URL cuối, DNS đích và tín hiệu preview xã hội.",
      th: "ตรวจ status, URL สุดท้าย, DNS target และสัญญาณ social preview",
      ar: "افحص status والرابط النهائي وهدف DNS وإشارات المعاينة الاجتماعية.",
    }),
    searchIntents: ["redirect chain checker", "http status redirect", "canonical redirect debug", "www apex redirect"],
    steps: [
      {
        toolSlug: "http-status-checker",
        reason: localized({
          en: "Follow the redirect chain and final response.",
          ko: "redirect chain과 최종 응답을 따라갑니다.",
          ja: "redirect chainと最終レスポンスを追跡します。",
          "zh-CN": "跟踪 redirect chain 和最终响应。",
          "zh-TW": "追蹤 redirect chain 與最終回應。",
          es: "Sigue la cadena de redireccion y la respuesta final.",
          "pt-BR": "Siga a cadeia de redirecionamento e a resposta final.",
          de: "Verfolge Redirect-Kette und finale Antwort.",
          fr: "Suivez la chaine de redirection et la reponse finale.",
          hi: "redirect chain और final response देखें.",
          id: "Ikuti rantai redirect dan respons akhir.",
          vi: "Theo dõi chuỗi redirect và phản hồi cuối.",
          th: "ตาม redirect chain และ response สุดท้าย",
          ar: "تتبع سلسلة redirect والاستجابة النهائية.",
        }),
      },
      {
        toolSlug: "dns-lookup",
        reason: localized({
          en: "Confirm apex, www, and CNAME records point where expected.",
          ko: "apex, www, CNAME 레코드가 예상한 대상으로 향하는지 확인합니다.",
          ja: "apex、www、CNAMEが想定先を向くか確認します。",
          "zh-CN": "确认 apex、www 和 CNAME 记录是否指向预期目标。",
          "zh-TW": "確認 apex、www 與 CNAME 紀錄是否指向預期目標。",
          es: "Confirma que apex, www y CNAME apunten al destino esperado.",
          "pt-BR": "Confirme se apex, www e CNAME apontam para o destino esperado.",
          de: "Pruefe, ob Apex, www und CNAME auf das erwartete Ziel zeigen.",
          fr: "Confirmez que apex, www et CNAME pointent vers la bonne cible.",
          hi: "apex, www और CNAME records सही target पर हैं या नहीं देखें.",
          id: "Pastikan apex, www, dan CNAME mengarah ke target yang benar.",
          vi: "Xác nhận apex, www và CNAME trỏ tới đúng đích.",
          th: "ยืนยัน apex, www และ CNAME ชี้ไปยังเป้าหมายที่ถูกต้อง",
          ar: "تأكد أن apex وwww وCNAME تشير إلى الهدف المتوقع.",
        }),
      },
      {
        toolSlug: "url-parser",
        reason: localized({
          en: "Break down query parameters and canonical path changes.",
          ko: "query parameter와 canonical path 변경을 분해해 봅니다.",
          ja: "query parameterとcanonical pathの変更を分解します。",
          "zh-CN": "拆解 query 参数和 canonical path 变化。",
          "zh-TW": "拆解 query 參數與 canonical path 變化。",
          es: "Descompone parametros query y cambios de ruta canonica.",
          "pt-BR": "Separe parametros de query e mudancas de caminho canonico.",
          de: "Zerlege Query-Parameter und Canonical-Pfad-Aenderungen.",
          fr: "Detaillez les parametres query et changements de chemin canonique.",
          hi: "query parameters और canonical path बदलाव अलग करें.",
          id: "Urai parameter query dan perubahan path canonical.",
          vi: "Tách query parameter và thay đổi canonical path.",
          th: "แยก query parameter และการเปลี่ยน canonical path",
          ar: "فصل query parameters وتغييرات المسار canonical.",
        }),
      },
    ],
  },
  {
    slug: "inspect-image-data-url",
    title: localized({
      en: "Inspect an image data URL",
      ko: "이미지 data URL 점검",
      ja: "画像data URLを確認",
      "zh-CN": "检查图片 data URL",
      "zh-TW": "檢查圖片 data URL",
      es: "Revisar una data URL de imagen",
      "pt-BR": "Inspecionar data URL de imagem",
      de: "Bild-Data-URL pruefen",
      fr: "Inspecter une data URL image",
      hi: "image data URL जांचें",
      id: "Periksa data URL gambar",
      vi: "Kiểm tra data URL ảnh",
      th: "ตรวจ data URL ของรูปภาพ",
      ar: "فحص data URL لصورة",
    }),
    description: localized({
      en: "Preview Base64 image data, confirm the MIME type, then check presentation contrast before sharing.",
      ko: "Base64 이미지 데이터를 미리보고 MIME type을 확인한 뒤 공유 전 표시 대비를 점검합니다.",
      ja: "Base64画像データをプレビューし、MIME typeを確認して共有前に表示コントラストを見ます。",
      "zh-CN": "预览 Base64 图片数据，确认 MIME type，再检查分享前的显示对比度。",
      "zh-TW": "預覽 Base64 圖片資料，確認 MIME type，再檢查分享前的顯示對比。",
      es: "Previsualiza imagen Base64, confirma el MIME type y revisa contraste antes de compartir.",
      "pt-BR": "Preveja imagem Base64, confirme o MIME type e revise contraste antes de compartilhar.",
      de: "Vorschau fuer Base64-Bilddaten, MIME-Type pruefen und Kontrast vor dem Teilen kontrollieren.",
      fr: "Previsualisez l'image Base64, confirmez le MIME type et verifiez le contraste avant partage.",
      hi: "Base64 image preview करें, MIME type जांचें, फिर share से पहले contrast देखें.",
      id: "Pratinjau gambar Base64, pastikan MIME type, lalu cek kontras sebelum dibagikan.",
      vi: "Xem trước ảnh Base64, xác nhận MIME type rồi kiểm tra tương phản trước khi chia sẻ.",
      th: "ดูตัวอย่างรูป Base64 ยืนยัน MIME type แล้วตรวจ contrast ก่อนแชร์",
      ar: "عاين صورة Base64 وتأكد من MIME type ثم افحص التباين قبل المشاركة.",
    }),
    searchIntents: ["base64 image decoder", "data url decoder", "base64 to png", "image data url preview", "png base64 preview"],
    steps: [
      {
        toolSlug: "base64-tool",
        reason: localized({
          en: "Detect image bytes and preview the data URL without copying binary text.",
          ko: "binary 텍스트를 복사하지 않고 이미지 byte와 data URL 미리보기를 확인합니다.",
          ja: "binary textをコピーせず画像byteとdata URLプレビューを確認します。",
          "zh-CN": "不复制二进制文本，检测图片 byte 并预览 data URL。",
          "zh-TW": "不複製二進位文字，偵測圖片 byte 並預覽 data URL。",
          es: "Detecta bytes de imagen y previsualiza la data URL sin copiar texto binario.",
          "pt-BR": "Detecte bytes de imagem e preveja a data URL sem copiar texto binario.",
          de: "Erkenne Bild-Bytes und zeige die Data-URL, ohne Binaertext zu kopieren.",
          fr: "Detectez les octets image et previsualisez la data URL sans copier de binaire.",
          hi: "binary text copy किए बिना image bytes और data URL preview देखें.",
          id: "Deteksi byte gambar dan pratinjau data URL tanpa menyalin teks biner.",
          vi: "Nhận diện byte ảnh và xem data URL mà không sao chép văn bản nhị phân.",
          th: "ตรวจ byte รูปและดู data URL โดยไม่ต้องคัดลอก binary text",
          ar: "اكتشف بايتات الصورة وعاين data URL دون نسخ نص ثنائي.",
        }),
      },
      {
        toolSlug: "mime-type-lookup",
        reason: localized({
          en: "Confirm the extension and content type used by the image.",
          ko: "이미지에 맞는 확장자와 content type을 확인합니다.",
          ja: "画像に合う拡張子とcontent typeを確認します。",
          "zh-CN": "确认图片使用的扩展名和 content type。",
          "zh-TW": "確認圖片使用的副檔名與 content type。",
          es: "Confirma extension y content type de la imagen.",
          "pt-BR": "Confirme extensao e content type da imagem.",
          de: "Pruefe Erweiterung und Content-Type des Bildes.",
          fr: "Confirmez l'extension et le content type de l'image.",
          hi: "image की extension और content type जांचें.",
          id: "Pastikan ekstensi dan content type gambar.",
          vi: "Xác nhận đuôi file và content type của ảnh.",
          th: "ยืนยัน extension และ content type ของรูป",
          ar: "تأكد من الامتداد وcontent type للصورة.",
        }),
      },
      {
        toolSlug: "color-converter",
        reason: localized({
          en: "Check contrast when the image is used in a QR, badge, or document background.",
          ko: "이미지가 QR, badge, 문서 배경에 쓰일 때 대비를 확인합니다.",
          ja: "画像をQR、badge、文書背景で使う前にコントラストを確認します。",
          "zh-CN": "图片用于 QR、badge 或文档背景时检查对比度。",
          "zh-TW": "圖片用於 QR、badge 或文件背景時檢查對比。",
          es: "Revisa contraste si la imagen se usa en QR, badge o fondo de documento.",
          "pt-BR": "Revise contraste quando a imagem for usada em QR, badge ou fundo de documento.",
          de: "Pruefe Kontrast, wenn das Bild in QR, Badge oder Dokumenthintergrund landet.",
          fr: "Verifiez le contraste si l'image sert a un QR, badge ou fond de document.",
          hi: "image QR, badge या document background में हो तो contrast जांचें.",
          id: "Cek kontras saat gambar dipakai di QR, badge, atau latar dokumen.",
          vi: "Kiểm tra tương phản khi ảnh dùng trong QR, badge hoặc nền tài liệu.",
          th: "ตรวจ contrast เมื่อรูปใช้ใน QR, badge หรือพื้นหลังเอกสาร",
          ar: "افحص التباين عند استخدام الصورة في QR أو badge أو خلفية مستند.",
        }),
      },
    ],
  },
  {
    slug: "check-dns-deployment",
    title: localized({
      en: "Check a DNS deployment",
      ko: "DNS 배포 확인",
      ja: "DNSデプロイを確認",
      "zh-CN": "检查 DNS 发布",
      "zh-TW": "檢查 DNS 部署",
      es: "Revisar despliegue DNS",
      "pt-BR": "Verificar deploy DNS",
      de: "DNS-Deployment pruefen",
      fr: "Verifier un deploiement DNS",
      hi: "DNS deployment जांचें",
      id: "Cek deployment DNS",
      vi: "Kiểm tra triển khai DNS",
      th: "ตรวจ DNS deployment",
      ar: "فحص نشر DNS",
    }),
    description: localized({
      en: "Verify records, HTTP reachability, sitemap exposure, and robots rules after a domain change.",
      ko: "도메인 변경 후 레코드, HTTP 접근, sitemap 노출, robots 규칙을 확인합니다.",
      ja: "ドメイン変更後のrecord、HTTP到達性、sitemap、robotsルールを確認します。",
      "zh-CN": "域名变更后检查记录、HTTP 可达性、sitemap 和 robots 规则。",
      "zh-TW": "網域變更後檢查紀錄、HTTP 可達性、sitemap 與 robots 規則。",
      es: "Verifica registros, alcance HTTP, sitemap y reglas robots tras cambiar dominio.",
      "pt-BR": "Verifique registros, alcance HTTP, sitemap e regras robots apos mudar dominio.",
      de: "Pruefe Records, HTTP-Erreichbarkeit, Sitemap und robots-Regeln nach Domain-Aenderungen.",
      fr: "Verifiez records, acces HTTP, sitemap et regles robots apres changement de domaine.",
      hi: "domain बदलने के बाद records, HTTP, sitemap और robots rules जांचें.",
      id: "Periksa record, akses HTTP, sitemap, dan aturan robots setelah perubahan domain.",
      vi: "Kiểm tra record, HTTP, sitemap và robots sau khi đổi domain.",
      th: "ตรวจ record, HTTP, sitemap และ robots หลังเปลี่ยน domain",
      ar: "تحقق من records وHTTP وsitemap وrobots بعد تغيير النطاق.",
    }),
    searchIntents: ["dns propagation checklist", "domain deployment check", "www apex dns", "sitemap robots check"],
    steps: [
      { toolSlug: "dns-lookup", reason: localized({
        en: "Check A, AAAA, CNAME, MX, TXT, and NS records.",
        ko: "A, AAAA, CNAME, MX, TXT, NS 레코드를 확인합니다.",
        ja: "A、AAAA、CNAME、MX、TXT、NSレコードを確認します。",
        "zh-CN": "检查 A、AAAA、CNAME、MX、TXT、NS 记录。",
        "zh-TW": "檢查 A、AAAA、CNAME、MX、TXT、NS 紀錄。",
        es: "Revisa registros A, AAAA, CNAME, MX, TXT y NS.",
        "pt-BR": "Revise registros A, AAAA, CNAME, MX, TXT e NS.",
        de: "Pruefe A-, AAAA-, CNAME-, MX-, TXT- und NS-Records.",
        fr: "Verifiez les records A, AAAA, CNAME, MX, TXT et NS.",
        hi: "A, AAAA, CNAME, MX, TXT और NS records जांचें.",
        id: "Cek record A, AAAA, CNAME, MX, TXT, dan NS.",
        vi: "Kiểm tra record A, AAAA, CNAME, MX, TXT và NS.",
        th: "ตรวจ record A, AAAA, CNAME, MX, TXT และ NS",
        ar: "افحص سجلات A وAAAA وCNAME وMX وTXT وNS.",
      }) },
      { toolSlug: "http-status-checker", reason: localized({
        en: "Confirm the public URL returns the expected status.",
        ko: "공개 URL이 예상한 status를 반환하는지 확인합니다.",
        ja: "公開URLが期待するstatusを返すか確認します。",
        "zh-CN": "确认公开 URL 返回预期 status。",
        "zh-TW": "確認公開 URL 回傳預期 status。",
        es: "Confirma que la URL publica devuelva el status esperado.",
        "pt-BR": "Confirme se a URL publica retorna o status esperado.",
        de: "Pruefe, ob die oeffentliche URL den erwarteten Status liefert.",
        fr: "Confirmez que l'URL publique renvoie le status attendu.",
        hi: "public URL expected status देता है या नहीं देखें.",
        id: "Pastikan URL publik memberi status yang diharapkan.",
        vi: "Xác nhận URL công khai trả về status mong đợi.",
        th: "ยืนยัน URL สาธารณะคืน status ที่คาดไว้",
        ar: "تأكد أن الرابط العام يرجع status المتوقع.",
      }) },
      { toolSlug: "sitemap-generator", reason: localized({
        en: "Prepare clean sitemap URLs after routing is stable.",
        ko: "라우팅이 안정된 뒤 깨끗한 sitemap URL을 준비합니다.",
        ja: "ルーティング安定後にsitemap URLを整えます。",
        "zh-CN": "路由稳定后准备干净的 sitemap URL。",
        "zh-TW": "路由穩定後準備乾淨的 sitemap URL。",
        es: "Prepara URLs limpias de sitemap cuando el routing este estable.",
        "pt-BR": "Prepare URLs limpas de sitemap quando o roteamento estiver estavel.",
        de: "Bereite saubere Sitemap-URLs vor, sobald Routing stabil ist.",
        fr: "Preparez des URLs sitemap propres lorsque le routage est stable.",
        hi: "routing stable होने के बाद साफ sitemap URLs बनाएं.",
        id: "Siapkan URL sitemap bersih setelah routing stabil.",
        vi: "Chuẩn bị URL sitemap sạch sau khi routing ổn định.",
        th: "เตรียม sitemap URL ที่สะอาดเมื่อ routing เสถียร",
        ar: "جهز روابط sitemap نظيفة بعد استقرار التوجيه.",
      }) },
    ],
  },
  {
    slug: "create-wifi-qr",
    title: localized({
      en: "Create a Wi-Fi QR",
      ko: "Wi-Fi QR 만들기",
      ja: "Wi-Fi QRを作成",
      "zh-CN": "创建 Wi-Fi QR",
      "zh-TW": "建立 Wi-Fi QR",
      es: "Crear QR de Wi-Fi",
      "pt-BR": "Criar QR de Wi-Fi",
      de: "Wi-Fi-QR erstellen",
      fr: "Creer un QR Wi-Fi",
      hi: "Wi-Fi QR बनाएं",
      id: "Buat QR Wi-Fi",
      vi: "Tạo QR Wi-Fi",
      th: "สร้าง Wi-Fi QR",
      ar: "إنشاء QR للواي فاي",
    }),
    description: localized({
      en: "Generate a compatible network password, build the Wi-Fi payload, and check contrast before sharing.",
      ko: "호환되는 네트워크 비밀번호를 만들고 Wi-Fi payload를 구성한 뒤 대비를 확인합니다.",
      ja: "互換性のあるネットワークパスワードを作り、Wi-Fi payloadを組み立て、共有前にコントラストを確認します。",
      "zh-CN": "生成兼容的网络密码，构建 Wi-Fi payload，并在分享前检查对比度。",
      "zh-TW": "產生相容的網路密碼，建立 Wi-Fi payload，分享前檢查對比。",
      es: "Genera una contrasena compatible, arma el payload Wi-Fi y revisa contraste.",
      "pt-BR": "Gere uma senha compativel, monte o payload Wi-Fi e revise contraste.",
      de: "Erzeuge ein kompatibles Netzwerkpasswort, baue den Wi-Fi-Payload und pruefe Kontrast.",
      fr: "Generez un mot de passe compatible, construisez le payload Wi-Fi et verifiez le contraste.",
      hi: "compatible network password बनाएं, Wi-Fi payload तैयार करें और contrast जांचें.",
      id: "Buat kata sandi jaringan, susun payload Wi-Fi, lalu cek kontras.",
      vi: "Tạo mật khẩu mạng, dựng payload Wi-Fi và kiểm tra tương phản.",
      th: "สร้างรหัสผ่านเครือข่าย ประกอบ Wi-Fi payload แล้วตรวจ contrast",
      ar: "انشئ كلمة مرور شبكة مناسبة وابن payload للواي فاي وافحص التباين.",
    }),
    searchIntents: ["wifi qr code generator", "wifi password qr", "qr code contrast", "network qr workflow"],
    steps: [
      { toolSlug: "password-generator", reason: localized({
        en: "Generate a password that fits the router policy.",
        ko: "공유기 정책에 맞는 비밀번호를 생성합니다.",
        ja: "ルーターのポリシーに合うパスワードを生成します。",
        "zh-CN": "生成符合路由器策略的密码。",
        "zh-TW": "產生符合路由器規則的密碼。",
        es: "Genera una contrasena que encaje con la politica del router.",
        "pt-BR": "Gere uma senha que siga a politica do roteador.",
        de: "Erzeuge ein Passwort passend zur Router-Richtlinie.",
        fr: "Generez un mot de passe compatible avec la politique du routeur.",
        hi: "router policy के अनुसार password बनाएं.",
        id: "Buat kata sandi sesuai kebijakan router.",
        vi: "Tạo mật khẩu phù hợp chính sách router.",
        th: "สร้างรหัสผ่านที่ตรงกับ policy ของ router",
        ar: "انشئ كلمة مرور توافق سياسة الراوتر.",
      }) },
      { toolSlug: "qr-code-generator", reason: localized({
        en: "Build the Wi-Fi payload and download the QR image.",
        ko: "Wi-Fi payload를 만들고 QR 이미지를 내려받습니다.",
        ja: "Wi-Fi payloadを作りQR画像をダウンロードします。",
        "zh-CN": "构建 Wi-Fi payload 并下载 QR 图片。",
        "zh-TW": "建立 Wi-Fi payload 並下載 QR 圖片。",
        es: "Arma el payload Wi-Fi y descarga la imagen QR.",
        "pt-BR": "Monte o payload Wi-Fi e baixe a imagem QR.",
        de: "Baue den Wi-Fi-Payload und lade das QR-Bild herunter.",
        fr: "Construisez le payload Wi-Fi et telechargez l'image QR.",
        hi: "Wi-Fi payload बनाएं और QR image डाउनलोड करें.",
        id: "Susun payload Wi-Fi dan unduh gambar QR.",
        vi: "Dựng payload Wi-Fi và tải ảnh QR.",
        th: "ประกอบ Wi-Fi payload และดาวน์โหลดภาพ QR",
        ar: "ابن payload للواي فاي وحمل صورة QR.",
      }) },
      { toolSlug: "color-converter", reason: localized({
        en: "Check foreground and background contrast before printing.",
        ko: "출력 전에 전경/배경 대비를 확인합니다.",
        ja: "印刷前に前景色と背景色のコントラストを確認します。",
        "zh-CN": "打印前检查前景和背景对比度。",
        "zh-TW": "列印前檢查前景與背景對比。",
        es: "Revisa contraste de frente y fondo antes de imprimir.",
        "pt-BR": "Revise contraste de frente e fundo antes de imprimir.",
        de: "Pruefe Vorder- und Hintergrundkontrast vor dem Drucken.",
        fr: "Verifiez le contraste avant-plan/arriere-plan avant impression.",
        hi: "print से पहले foreground और background contrast जांचें.",
        id: "Cek kontras depan dan latar sebelum dicetak.",
        vi: "Kiểm tra tương phản trước khi in.",
        th: "ตรวจ contrast ระหว่าง foreground/background ก่อนพิมพ์",
        ar: "افحص تباين المقدمة والخلفية قبل الطباعة.",
      }) },
    ],
  },
  {
    slug: "generate-secure-token",
    title: localized({
      en: "Generate a secure token",
      ko: "보안 토큰 생성",
      ja: "安全なトークンを生成",
      "zh-CN": "生成安全 token",
      "zh-TW": "產生安全 token",
      es: "Generar token seguro",
      "pt-BR": "Gerar token seguro",
      de: "Sicheren Token erzeugen",
      fr: "Generer un token securise",
      hi: "secure token बनाएं",
      id: "Buat token aman",
      vi: "Tạo token an toàn",
      th: "สร้าง token ที่ปลอดภัย",
      ar: "إنشاء رمز آمن",
    }),
    description: localized({
      en: "Create random session/API/CSRF values, compare hashes, and choose identifiers deliberately.",
      ko: "session/API/CSRF 값을 만들고 hash를 비교하며 식별자를 의도에 맞게 고릅니다.",
      ja: "session/API/CSRF値を作り、hashを比較し、識別子を用途に合わせて選びます。",
      "zh-CN": "创建 session/API/CSRF 值，比较 hash，并按用途选择标识符。",
      "zh-TW": "建立 session/API/CSRF 值，比對 hash，並依用途選擇識別符。",
      es: "Crea valores session/API/CSRF, compara hashes y elige identificadores con cuidado.",
      "pt-BR": "Crie valores session/API/CSRF, compare hashes e escolha identificadores com cuidado.",
      de: "Erzeuge Session/API/CSRF-Werte, vergleiche Hashes und waehle IDs bewusst.",
      fr: "Creez des valeurs session/API/CSRF, comparez les hashes et choisissez les identifiants.",
      hi: "session/API/CSRF values बनाएं, hashes मिलाएं और identifiers सही चुनें.",
      id: "Buat nilai session/API/CSRF, bandingkan hash, dan pilih identifier dengan sadar.",
      vi: "Tạo giá trị session/API/CSRF, so sánh hash và chọn định danh đúng mục đích.",
      th: "สร้างค่า session/API/CSRF เทียบ hash และเลือก identifier ให้เหมาะ",
      ar: "انشئ قيم session/API/CSRF وقارن hashes واختر المعرفات بعناية.",
    }),
    searchIntents: ["csrf token generator", "api key generator", "secure random token", "uuid vs token"],
    steps: [
      { toolSlug: "random-token-generator", reason: localized({
        en: "Generate URL-safe session, API, CSRF, or webhook tokens.",
        ko: "URL-safe session, API, CSRF, webhook 토큰을 생성합니다.",
        ja: "URL-safeなsession、API、CSRF、webhook tokenを生成します。",
        "zh-CN": "生成 URL-safe 的 session、API、CSRF 或 webhook token。",
        "zh-TW": "產生 URL-safe 的 session、API、CSRF 或 webhook token。",
        es: "Genera tokens URL-safe para session, API, CSRF o webhook.",
        "pt-BR": "Gere tokens URL-safe para session, API, CSRF ou webhook.",
        de: "Erzeuge URL-sichere Session-, API-, CSRF- oder Webhook-Tokens.",
        fr: "Generez des tokens URL-safe pour session, API, CSRF ou webhook.",
        hi: "URL-safe session, API, CSRF या webhook tokens बनाएं.",
        id: "Buat token URL-safe untuk session, API, CSRF, atau webhook.",
        vi: "Tạo token URL-safe cho session, API, CSRF hoặc webhook.",
        th: "สร้าง token แบบ URL-safe สำหรับ session, API, CSRF หรือ webhook",
        ar: "انشئ tokens آمنة للروابط للجلسات وAPI وCSRF وwebhook.",
      }) },
      { toolSlug: "hash-generator", reason: localized({
        en: "Compare digest or HMAC output for signatures.",
        ko: "서명에 필요한 digest나 HMAC 결과를 비교합니다.",
        ja: "署名に必要なdigestやHMAC出力を比較します。",
        "zh-CN": "比较签名所需的 digest 或 HMAC 输出。",
        "zh-TW": "比較簽章所需的 digest 或 HMAC 輸出。",
        es: "Compara digest o salida HMAC para firmas.",
        "pt-BR": "Compare digest ou saida HMAC para assinaturas.",
        de: "Vergleiche Digest- oder HMAC-Ausgaben fuer Signaturen.",
        fr: "Comparez digest ou sortie HMAC pour les signatures.",
        hi: "signatures के लिए digest या HMAC output मिलाएं.",
        id: "Bandingkan digest atau output HMAC untuk signature.",
        vi: "So sánh digest hoặc HMAC cho chữ ký.",
        th: "เทียบ digest หรือ HMAC output สำหรับ signature",
        ar: "قارن digest أو ناتج HMAC للتواقيع.",
      }) },
      { toolSlug: "uuid-generator", reason: localized({
        en: "Use UUIDs for identifiers, not as secrets.",
        ko: "UUID는 secret이 아니라 식별자로 사용합니다.",
        ja: "UUIDはsecretではなく識別子として使います。",
        "zh-CN": "UUID 用作标识符，不当作 secret。",
        "zh-TW": "UUID 用作識別符，不當作 secret。",
        es: "Usa UUID como identificadores, no como secretos.",
        "pt-BR": "Use UUIDs como identificadores, nao como segredos.",
        de: "Nutze UUIDs als Bezeichner, nicht als Secrets.",
        fr: "Utilisez les UUID comme identifiants, pas comme secrets.",
        hi: "UUID को secret नहीं, identifier की तरह इस्तेमाल करें.",
        id: "Gunakan UUID sebagai identifier, bukan secret.",
        vi: "Dùng UUID làm định danh, không dùng như secret.",
        th: "ใช้ UUID เป็น identifier ไม่ใช่ secret",
        ar: "استخدم UUID كمعرفات وليس كاسرار.",
      }) },
    ],
  },
];

function localizeRecipe(recipe: WorkflowRecipe, locale: Locale, tools: ToolDefinition[]): LocalizedWorkflowRecipe | undefined {
  const toolBySlug = new Map(tools.map((tool) => [tool.slug, tool]));
  const steps = recipe.steps
    .map((step) => {
      const tool = toolBySlug.get(step.toolSlug);
      if (!tool) return undefined;
      return { tool, reason: text(step.reason, locale) };
    })
    .filter((step): step is LocalizedWorkflowStep => Boolean(step));

  if (steps.length < 2) return undefined;
  return {
    slug: recipe.slug,
    title: text(recipe.title, locale),
    description: text(recipe.description, locale),
    searchIntents: recipe.searchIntents,
    steps,
  };
}

export function getLocalizedWorkflowRecipes(locale: Locale, tools: ToolDefinition[]) {
  return workflowRecipes
    .map((recipe) => localizeRecipe(recipe, locale, tools))
    .filter((recipe): recipe is LocalizedWorkflowRecipe => Boolean(recipe));
}

export function getWorkflowRecipesForTool(toolSlug: string, locale: Locale, tools: ToolDefinition[], limit = 3) {
  return getLocalizedWorkflowRecipes(locale, tools)
    .filter((recipe) => recipe.steps.some((step) => step.tool.slug === toolSlug))
    .sort((a, b) => {
      const aIndex = a.steps.findIndex((step) => step.tool.slug === toolSlug);
      const bIndex = b.steps.findIndex((step) => step.tool.slug === toolSlug);
      return aIndex - bIndex || a.title.localeCompare(b.title);
    })
    .slice(0, limit);
}
