import type { Locale } from "@/features/i18n/config";
import type { ToolDefinition } from "./types";

type LocalizedText = Record<Locale, string>;

export interface WorkflowStep {
  toolSlug: string;
  reason: LocalizedText;
}

export interface WorkflowRecipe {
  slug: string;
  title: LocalizedText;
  description: LocalizedText;
  searchIntents: string[];
  steps: WorkflowStep[];
}

export interface LocalizedWorkflowStep {
  tool: ToolDefinition;
  reason: string;
}

export interface LocalizedWorkflowRecipe {
  slug: string;
  title: string;
  description: string;
  searchIntents: string[];
  steps: LocalizedWorkflowStep[];
}

const text = (values: LocalizedText, locale: Locale) => values[locale] ?? values.en;

const localized = (values: LocalizedText) => values;

export const workflowRecipes: WorkflowRecipe[] = [
  {
    slug: "format-api-response",
    title: localized({
      en: "Format an API response",
      ko: "API 응답 정리",
      ja: "APIレスポンスを整える",
      "zh-CN": "整理 API 响应",
      "zh-TW": "整理 API 回應",
      es: "Formatear una respuesta API",
      "pt-BR": "Formatar uma resposta de API",
      de: "API-Antwort formatieren",
      fr: "Formater une reponse API",
      hi: "API response को व्यवस्थित करें",
      id: "Rapikan respons API",
      vi: "Định dạng phản hồi API",
      th: "จัดรูปแบบ response API",
      ar: "تنسيق استجابة API",
    }),
    description: localized({
      en: "Clean a pasted JSON payload, inspect paths, then create types or schema checks.",
      ko: "붙여 넣은 JSON을 정리하고 경로를 확인한 뒤 타입이나 스키마 검증으로 이어갑니다.",
      ja: "貼り付けたJSONを整形し、パスを確認して型やスキーマ確認へ進みます。",
      "zh-CN": "整理粘贴的 JSON，检查路径，再生成类型或做 schema 校验。",
      "zh-TW": "整理貼上的 JSON，檢查路徑，再產生型別或做 schema 驗證。",
      es: "Limpia JSON pegado, revisa rutas y sigue con tipos o validacion de esquema.",
      "pt-BR": "Limpe JSON colado, revise caminhos e siga para tipos ou schema.",
      de: "Bereinige eingefuegtes JSON, pruefe Pfade und erstelle Typen oder Schema-Checks.",
      fr: "Nettoyez un JSON colle, verifiez les chemins, puis creez types ou controles schema.",
      hi: "चिपकाए गए JSON को साफ करें, paths देखें, फिर types या schema जांच बनाएं.",
      id: "Bersihkan JSON tempel, periksa path, lalu buat tipe atau cek schema.",
      vi: "Làm sạch JSON đã dán, kiểm tra path rồi tạo type hoặc kiểm tra schema.",
      th: "จัด JSON ที่วาง ตรวจ path แล้วต่อด้วย type หรือ schema check",
      ar: "نظف JSON الملصق وافحص المسارات ثم أنشئ الانواع أو تحقق من schema.",
    }),
    searchIntents: ["api response formatter", "json response viewer", "json error line column", "json parse error context", "json to typescript workflow", "json schema check"],
    steps: [
      {
        toolSlug: "json-formatter",
        reason: localized({
          en: "Validate and format the payload before copying it.",
          ko: "복사 전에 페이로드를 검증하고 보기 좋게 정리합니다.",
          ja: "コピー前にペイロードを検証して整形します。",
          "zh-CN": "复制前先验证并格式化 payload。",
          "zh-TW": "複製前先驗證並格式化 payload。",
          es: "Valida y formatea el payload antes de copiarlo.",
          "pt-BR": "Valide e formate o payload antes de copiar.",
          de: "Validiere und formatiere den Payload vor dem Kopieren.",
          fr: "Validez et formatez le payload avant copie.",
          hi: "कॉपी से पहले payload को validate और format करें.",
          id: "Validasi dan format payload sebelum disalin.",
          vi: "Xác thực và định dạng payload trước khi sao chép.",
          th: "ตรวจและจัด payload ก่อนคัดลอก",
          ar: "تحقق من payload ونسقه قبل النسخ.",
        }),
      },
      {
        toolSlug: "jsonpath-tester",
        reason: localized({
          en: "Pull the exact field path needed by code or docs.",
          ko: "코드나 문서에 필요한 정확한 필드 경로를 뽑습니다.",
          ja: "コードや文書に必要な正確なフィールドパスを取り出します。",
          "zh-CN": "取出代码或文档需要的精确字段路径。",
          "zh-TW": "取出程式或文件需要的精確欄位路徑。",
          es: "Extrae la ruta exacta del campo que necesita el codigo o la documentacion.",
          "pt-BR": "Extraia o caminho exato do campo usado no codigo ou docs.",
          de: "Extrahiere den genauen Feldpfad fuer Code oder Dokumentation.",
          fr: "Recuperez le chemin exact du champ pour le code ou la documentation.",
          hi: "code या docs के लिए सही field path निकालें.",
          id: "Ambil path field yang tepat untuk kode atau dokumentasi.",
          vi: "Lấy đúng path trường cần cho code hoặc tài liệu.",
          th: "ดึง path ของ field ที่ code หรือเอกสารต้องใช้",
          ar: "استخرج مسار الحقل الدقيق للكود أو المستندات.",
        }),
      },
      {
        toolSlug: "json-to-typescript",
        reason: localized({
          en: "Turn the sample shape into a starter interface.",
          ko: "샘플 구조를 TypeScript 인터페이스 초안으로 바꿉니다.",
          ja: "サンプル構造をTypeScript interfaceの下書きに変えます。",
          "zh-CN": "把样例结构转换成 TypeScript interface 草稿。",
          "zh-TW": "把範例結構轉成 TypeScript interface 草稿。",
          es: "Convierte la forma de ejemplo en una interfaz inicial.",
          "pt-BR": "Converta a estrutura de exemplo em uma interface inicial.",
          de: "Wandle die Beispielstruktur in ein erstes Interface um.",
          fr: "Transformez la structure d'exemple en interface de depart.",
          hi: "sample shape को शुरुआती interface में बदलें.",
          id: "Ubah bentuk contoh menjadi interface awal.",
          vi: "Chuyển cấu trúc mẫu thành interface ban đầu.",
          th: "เปลี่ยนโครงสร้างตัวอย่างเป็น interface เริ่มต้น",
          ar: "حول شكل العينة إلى interface مبدئي.",
        }),
      },
    ],
  },
  {
    slug: "extract-json-field",
    title: localized({
      en: "Extract a JSON field",
      ko: "JSON 필드 추출",
      ja: "JSONフィールドを抽出",
      "zh-CN": "提取 JSON 字段",
      "zh-TW": "擷取 JSON 欄位",
      es: "Extraer un campo JSON",
      "pt-BR": "Extrair campo JSON",
      de: "JSON-Feld extrahieren",
      fr: "Extraire un champ JSON",
      hi: "JSON field निकालें",
      id: "Ekstrak field JSON",
      vi: "Trích xuất trường JSON",
      th: "ดึง field จาก JSON",
      ar: "استخراج حقل JSON",
    }),
    description: localized({
      en: "Format the payload, test a path with wildcards or recursive keys, then keep the shape for code.",
      ko: "payload를 정리하고 wildcard나 recursive key 경로를 테스트한 뒤 코드에 쓸 구조를 남깁니다.",
      ja: "payloadを整形し、wildcardやrecursive keyのパスを試して、コードで使う形を残します。",
      "zh-CN": "格式化 payload，测试 wildcard 或递归键路径，再保留给代码使用的结构。",
      "zh-TW": "格式化 payload，測試 wildcard 或遞迴鍵路徑，再保留給程式使用的結構。",
      es: "Formatea el payload, prueba una ruta con wildcard o claves recursivas y conserva la forma para codigo.",
      "pt-BR": "Formate o payload, teste um caminho com wildcard ou chaves recursivas e mantenha a estrutura para codigo.",
      de: "Formatiere den Payload, teste Pfade mit Wildcards oder rekursiven Keys und behalte die Struktur fuer Code.",
      fr: "Formatez le payload, testez un chemin avec wildcard ou cles recursives, puis gardez la forme pour le code.",
      hi: "payload format करें, wildcard या recursive key path जांचें, फिर code के लिए shape रखें.",
      id: "Format payload, uji path wildcard atau key rekursif, lalu simpan bentuk untuk kode.",
      vi: "Định dạng payload, thử path wildcard hoặc khóa đệ quy rồi giữ cấu trúc cho code.",
      th: "จัดรูปแบบ payload ทดสอบ path แบบ wildcard หรือ key recursive แล้วเก็บโครงสร้างไว้ใช้กับ code",
      ar: "نسق payload واختبر مسارا مع wildcard أو مفاتيح recursive ثم احتفظ بالشكل للكود.",
    }),
    searchIntents: ["json field extractor", "json path extractor", "extract json value", "jsonpath wildcard", "recursive jsonpath"],
    steps: [
      {
        toolSlug: "json-formatter",
        reason: localized({
          en: "Format and validate the pasted response before selecting fields.",
          ko: "필드를 고르기 전에 붙여 넣은 응답을 정리하고 검증합니다.",
          ja: "フィールド選択前に貼り付けたレスポンスを整形して検証します。",
          "zh-CN": "选择字段前先格式化并验证粘贴的响应。",
          "zh-TW": "選擇欄位前先格式化並驗證貼上的回應。",
          es: "Formatea y valida la respuesta pegada antes de elegir campos.",
          "pt-BR": "Formate e valide a resposta colada antes de escolher campos.",
          de: "Formatiere und validiere die eingefuegte Antwort vor der Feldauswahl.",
          fr: "Formatez et validez la reponse collee avant de choisir les champs.",
          hi: "field चुनने से पहले pasted response format और validate करें.",
          id: "Format dan validasi respons yang ditempel sebelum memilih field.",
          vi: "Định dạng và xác thực phản hồi đã dán trước khi chọn trường.",
          th: "จัดรูปแบบและตรวจ response ที่วางก่อนเลือก field",
          ar: "نسق الاستجابة الملصقة وتحقق منها قبل اختيار الحقول.",
        }),
      },
      {
        toolSlug: "jsonpath-tester",
        reason: localized({
          en: "Test dot paths, bracket keys, wildcards, and recursive key searches.",
          ko: "dot path, bracket key, wildcard, recursive key 검색을 테스트합니다.",
          ja: "dot path、bracket key、wildcard、recursive key検索を試します。",
          "zh-CN": "测试 dot path、bracket key、wildcard 和递归键搜索。",
          "zh-TW": "測試 dot path、bracket key、wildcard 與遞迴鍵搜尋。",
          es: "Prueba dot paths, claves con brackets, wildcards y busquedas recursivas.",
          "pt-BR": "Teste dot paths, chaves com brackets, wildcards e buscas recursivas.",
          de: "Teste Dot-Pfade, Bracket-Keys, Wildcards und rekursive Key-Suchen.",
          fr: "Testez dot paths, cles bracket, wildcards et recherches recursives.",
          hi: "dot path, bracket key, wildcard और recursive key search जांचें.",
          id: "Uji dot path, key bracket, wildcard, dan pencarian key rekursif.",
          vi: "Thử dot path, khóa bracket, wildcard và tìm khóa đệ quy.",
          th: "ทดสอบ dot path, key แบบ bracket, wildcard และการค้น key แบบ recursive",
          ar: "اختبر dot path ومفاتيح bracket وwildcard والبحث recursive.",
        }),
      },
      {
        toolSlug: "json-to-typescript",
        reason: localized({
          en: "Create a starter type once the field shape is clear.",
          ko: "필드 구조가 명확해지면 TypeScript 타입 초안을 만듭니다.",
          ja: "フィールド構造が明確になったらTypeScript型の下書きを作ります。",
          "zh-CN": "字段结构明确后生成 TypeScript 类型草稿。",
          "zh-TW": "欄位結構明確後產生 TypeScript 型別草稿。",
          es: "Crea un tipo inicial cuando la forma del campo este clara.",
          "pt-BR": "Crie um tipo inicial quando a estrutura do campo estiver clara.",
          de: "Erstelle einen Starttyp, sobald die Feldstruktur klar ist.",
          fr: "Creez un type de depart une fois la forme du champ claire.",
          hi: "field shape साफ होने पर starter type बनाएं.",
          id: "Buat tipe awal setelah bentuk field jelas.",
          vi: "Tạo type ban đầu khi cấu trúc trường đã rõ.",
          th: "สร้าง type เริ่มต้นเมื่อโครงสร้าง field ชัดเจน",
          ar: "أنشئ نوعا مبدئيا عندما يصبح شكل الحقل واضحا.",
        }),
      },
    ],
  },
  {
    slug: "decode-api-token",
    title: localized({
      en: "Decode an API token",
      ko: "API 토큰 확인",
      ja: "APIトークンを確認",
      "zh-CN": "解读 API token",
      "zh-TW": "解讀 API token",
      es: "Decodificar un token API",
      "pt-BR": "Decodificar token de API",
      de: "API-Token pruefen",
      fr: "Decoder un token API",
      hi: "API token जांचें",
      id: "Periksa token API",
      vi: "Giải mã token API",
      th: "ตรวจ token API",
      ar: "فك ترميز رمز API",
    }),
    description: localized({
      en: "Inspect JWT claims, check time fields, and compare encoded segments safely.",
      ko: "JWT 클레임과 시간 필드를 확인하고 인코딩된 세그먼트를 안전하게 비교합니다.",
      ja: "JWT claimと時刻フィールドを確認し、エンコード済みセグメントを安全に比較します。",
      "zh-CN": "检查 JWT claim 和时间字段，并安全比较编码片段。",
      "zh-TW": "檢查 JWT claim 和時間欄位，並安全比較編碼片段。",
      es: "Revisa claims JWT, campos de tiempo y segmentos codificados con cuidado.",
      "pt-BR": "Revise claims JWT, campos de tempo e segmentos codificados com cuidado.",
      de: "Pruefe JWT-Claims, Zeitfelder und codierte Segmente sicher.",
      fr: "Inspectez les claims JWT, les champs de temps et les segments encodes.",
      hi: "JWT claims, time fields और encoded segments को सावधानी से देखें.",
      id: "Periksa claim JWT, field waktu, dan segmen terkode dengan aman.",
      vi: "Kiểm tra claim JWT, trường thời gian và đoạn mã hóa an toàn.",
      th: "ตรวจ claim JWT เวลา และ segment ที่ encode อย่างปลอดภัย",
      ar: "افحص claims في JWT وحقول الوقت والمقاطع المشفرة بأمان.",
    }),
    searchIntents: ["jwt exp checker", "api token decoder", "base64url jwt payload", "jwt authorization header", "jwt claim inspector", "jwt sensitive claims", "jwt redacted payload", "jwt issuer checker", "jwt audience checker", "jwt scope checker", "token expiry debug"],
    steps: [
      {
        toolSlug: "jwt-decoder",
        reason: localized({
          en: "Read header and payload without sending the token to a verifier.",
          ko: "토큰을 검증 서버로 보내지 않고 header와 payload를 읽습니다.",
          ja: "検証サーバーに送らずheaderとpayloadを読みます。",
          "zh-CN": "不发送到验证器，直接读取 header 和 payload。",
          "zh-TW": "不送到驗證器，直接讀取 header 與 payload。",
          es: "Lee header y payload sin enviar el token a un verificador.",
          "pt-BR": "Leia header e payload sem enviar o token a um verificador.",
          de: "Lies Header und Payload, ohne den Token an einen Verifier zu senden.",
          fr: "Lisez header et payload sans envoyer le token a un verificateur.",
          hi: "token verifier को भेजे बिना header और payload पढ़ें.",
          id: "Baca header dan payload tanpa mengirim token ke verifier.",
          vi: "Đọc header và payload mà không gửi token tới trình xác minh.",
          th: "อ่าน header และ payload โดยไม่ส่ง token ไป verifier",
          ar: "اقرأ header وpayload دون إرسال الرمز إلى مدقق.",
        }),
      },
      {
        toolSlug: "timestamp-converter",
        reason: localized({
          en: "Convert exp, iat, and nbf values into readable dates.",
          ko: "exp, iat, nbf 값을 읽기 쉬운 날짜로 바꿉니다.",
          ja: "exp、iat、nbfを読みやすい日時に変換します。",
          "zh-CN": "把 exp、iat、nbf 转成可读日期。",
          "zh-TW": "把 exp、iat、nbf 轉成可讀日期。",
          es: "Convierte exp, iat y nbf en fechas legibles.",
          "pt-BR": "Converta exp, iat e nbf em datas legiveis.",
          de: "Wandle exp, iat und nbf in lesbare Daten um.",
          fr: "Convertissez exp, iat et nbf en dates lisibles.",
          hi: "exp, iat और nbf को पढ़ने योग्य dates में बदलें.",
          id: "Ubah exp, iat, dan nbf menjadi tanggal yang mudah dibaca.",
          vi: "Chuyển exp, iat và nbf thành ngày dễ đọc.",
          th: "แปลง exp, iat, nbf เป็นวันที่อ่านง่าย",
          ar: "حول exp وiat وnbf إلى تواريخ مفهومة.",
        }),
      },
      {
        toolSlug: "base64-tool",
        reason: localized({
          en: "Compare Base64URL segments and padding issues.",
          ko: "Base64URL 세그먼트와 padding 문제를 비교합니다.",
          ja: "Base64URLセグメントとpadding問題を比較します。",
          "zh-CN": "比较 Base64URL 片段和 padding 问题。",
          "zh-TW": "比較 Base64URL 片段與 padding 問題。",
          es: "Compara segmentos Base64URL y problemas de padding.",
          "pt-BR": "Compare segmentos Base64URL e problemas de padding.",
          de: "Vergleiche Base64URL-Segmente und Padding-Probleme.",
          fr: "Comparez les segments Base64URL et les problemes de padding.",
          hi: "Base64URL segments और padding issues की तुलना करें.",
          id: "Bandingkan segmen Base64URL dan masalah padding.",
          vi: "So sánh segment Base64URL và lỗi padding.",
          th: "เทียบ segment Base64URL และปัญหา padding",
          ar: "قارن مقاطع Base64URL ومشكلات padding.",
        }),
      },
    ],
  },
  {
    slug: "debug-redirect",
    title: localized({
      en: "Debug a redirect",
      ko: "리다이렉트 디버그",
      ja: "リダイレクトを調査",
      "zh-CN": "调试重定向",
      "zh-TW": "除錯重新導向",
      es: "Depurar una redireccion",
      "pt-BR": "Depurar redirecionamento",
      de: "Redirect debuggen",
      fr: "Deboguer une redirection",
      hi: "redirect जांचें",
      id: "Debug redirect",
      vi: "Gỡ lỗi redirect",
      th: "debug redirect",
      ar: "تصحيح redirect",
    }),
    description: localized({
      en: "Check status, final URL, DNS target, and social preview signals in one path.",
      ko: "status, 최종 URL, DNS 대상, social preview 신호를 한 흐름에서 확인합니다.",
      ja: "status、最終URL、DNS先、social previewの信号を一つの流れで確認します。",
      "zh-CN": "一次检查 status、最终 URL、DNS 目标和社交预览信号。",
      "zh-TW": "一次檢查 status、最終 URL、DNS 目標與社群預覽訊號。",
      es: "Revisa status, URL final, destino DNS y senales de vista social.",
      "pt-BR": "Verifique status, URL final, destino DNS e sinais de preview social.",
      de: "Pruefe Status, finale URL, DNS-Ziel und Social-Preview-Signale.",
      fr: "Verifiez status, URL finale, cible DNS et signaux de preview social.",
      hi: "status, final URL, DNS target और social preview signal साथ देखें.",
      id: "Cek status, URL akhir, target DNS, dan sinyal preview sosial.",
      vi: "Kiểm tra status, URL cuối, DNS đích và tín hiệu preview xã hội.",
      th: "ตรวจ status, URL สุดท้าย, DNS target และสัญญาณ social preview",
      ar: "افحص status والرابط النهائي وهدف DNS وإشارات المعاينة الاجتماعية.",
    }),
    searchIntents: ["redirect chain checker", "http status redirect", "canonical redirect debug", "www apex redirect"],
    steps: [
      {
        toolSlug: "http-status-checker",
        reason: localized({
          en: "Follow the redirect chain and final response.",
          ko: "redirect chain과 최종 응답을 따라갑니다.",
          ja: "redirect chainと最終レスポンスを追跡します。",
          "zh-CN": "跟踪 redirect chain 和最终响应。",
          "zh-TW": "追蹤 redirect chain 與最終回應。",
          es: "Sigue la cadena de redireccion y la respuesta final.",
          "pt-BR": "Siga a cadeia de redirecionamento e a resposta final.",
          de: "Verfolge Redirect-Kette und finale Antwort.",
          fr: "Suivez la chaine de redirection et la reponse finale.",
          hi: "redirect chain और final response देखें.",
          id: "Ikuti rantai redirect dan respons akhir.",
          vi: "Theo dõi chuỗi redirect và phản hồi cuối.",
          th: "ตาม redirect chain และ response สุดท้าย",
          ar: "تتبع سلسلة redirect والاستجابة النهائية.",
        }),
      },
      {
        toolSlug: "dns-lookup",
        reason: localized({
          en: "Confirm apex, www, and CNAME records point where expected.",
          ko: "apex, www, CNAME 레코드가 예상한 대상으로 향하는지 확인합니다.",
          ja: "apex、www、CNAMEが想定先を向くか確認します。",
          "zh-CN": "确认 apex、www 和 CNAME 记录是否指向预期目标。",
          "zh-TW": "確認 apex、www 與 CNAME 紀錄是否指向預期目標。",
          es: "Confirma que apex, www y CNAME apunten al destino esperado.",
          "pt-BR": "Confirme se apex, www e CNAME apontam para o destino esperado.",
          de: "Pruefe, ob Apex, www und CNAME auf das erwartete Ziel zeigen.",
          fr: "Confirmez que apex, www et CNAME pointent vers la bonne cible.",
          hi: "apex, www और CNAME records सही target पर हैं या नहीं देखें.",
          id: "Pastikan apex, www, dan CNAME mengarah ke target yang benar.",
          vi: "Xác nhận apex, www và CNAME trỏ tới đúng đích.",
          th: "ยืนยัน apex, www และ CNAME ชี้ไปยังเป้าหมายที่ถูกต้อง",
          ar: "تأكد أن apex وwww وCNAME تشير إلى الهدف المتوقع.",
        }),
      },
      {
        toolSlug: "url-parser",
        reason: localized({
          en: "Break down query parameters and canonical path changes.",
          ko: "query parameter와 canonical path 변경을 분해해 봅니다.",
          ja: "query parameterとcanonical pathの変更を分解します。",
          "zh-CN": "拆解 query 参数和 canonical path 变化。",
          "zh-TW": "拆解 query 參數與 canonical path 變化。",
          es: "Descompone parametros query y cambios de ruta canonica.",
          "pt-BR": "Separe parametros de query e mudancas de caminho canonico.",
          de: "Zerlege Query-Parameter und Canonical-Pfad-Aenderungen.",
          fr: "Detaillez les parametres query et changements de chemin canonique.",
          hi: "query parameters और canonical path बदलाव अलग करें.",
          id: "Urai parameter query dan perubahan path canonical.",
          vi: "Tách query parameter và thay đổi canonical path.",
          th: "แยก query parameter และการเปลี่ยน canonical path",
          ar: "فصل query parameters وتغييرات المسار canonical.",
        }),
      },
    ],
  },
  {
    slug: "inspect-image-data-url",
    title: localized({
      en: "Inspect an image data URL",
      ko: "이미지 data URL 점검",
      ja: "画像data URLを確認",
      "zh-CN": "检查图片 data URL",
      "zh-TW": "檢查圖片 data URL",
      es: "Revisar una data URL de imagen",
      "pt-BR": "Inspecionar data URL de imagem",
      de: "Bild-Data-URL pruefen",
      fr: "Inspecter une data URL image",
      hi: "image data URL जांचें",
      id: "Periksa data URL gambar",
      vi: "Kiểm tra data URL ảnh",
      th: "ตรวจ data URL ของรูปภาพ",
      ar: "فحص data URL لصورة",
    }),
    description: localized({
      en: "Preview Base64 image data, confirm the MIME type, then check presentation contrast before sharing.",
      ko: "Base64 이미지 데이터를 미리보고 MIME type을 확인한 뒤 공유 전 표시 대비를 점검합니다.",
      ja: "Base64画像データをプレビューし、MIME typeを確認して共有前に表示コントラストを見ます。",
      "zh-CN": "预览 Base64 图片数据，确认 MIME type，再检查分享前的显示对比度。",
      "zh-TW": "預覽 Base64 圖片資料，確認 MIME type，再檢查分享前的顯示對比。",
      es: "Previsualiza imagen Base64, confirma el MIME type y revisa contraste antes de compartir.",
      "pt-BR": "Preveja imagem Base64, confirme o MIME type e revise contraste antes de compartilhar.",
      de: "Vorschau fuer Base64-Bilddaten, MIME-Type pruefen und Kontrast vor dem Teilen kontrollieren.",
      fr: "Previsualisez l'image Base64, confirmez le MIME type et verifiez le contraste avant partage.",
      hi: "Base64 image preview करें, MIME type जांचें, फिर share से पहले contrast देखें.",
      id: "Pratinjau gambar Base64, pastikan MIME type, lalu cek kontras sebelum dibagikan.",
      vi: "Xem trước ảnh Base64, xác nhận MIME type rồi kiểm tra tương phản trước khi chia sẻ.",
      th: "ดูตัวอย่างรูป Base64 ยืนยัน MIME type แล้วตรวจ contrast ก่อนแชร์",
      ar: "عاين صورة Base64 وتأكد من MIME type ثم افحص التباين قبل المشاركة.",
    }),
    searchIntents: ["base64 image decoder", "data url decoder", "base64 to png", "download base64 image", "image data url preview", "png base64 preview"],
    steps: [
      {
        toolSlug: "base64-tool",
        reason: localized({
          en: "Detect image bytes and preview the data URL without copying binary text.",
          ko: "binary 텍스트를 복사하지 않고 이미지 byte와 data URL 미리보기를 확인합니다.",
          ja: "binary textをコピーせず画像byteとdata URLプレビューを確認します。",
          "zh-CN": "不复制二进制文本，检测图片 byte 并预览 data URL。",
          "zh-TW": "不複製二進位文字，偵測圖片 byte 並預覽 data URL。",
          es: "Detecta bytes de imagen y previsualiza la data URL sin copiar texto binario.",
          "pt-BR": "Detecte bytes de imagem e preveja a data URL sem copiar texto binario.",
          de: "Erkenne Bild-Bytes und zeige die Data-URL, ohne Binaertext zu kopieren.",
          fr: "Detectez les octets image et previsualisez la data URL sans copier de binaire.",
          hi: "binary text copy किए बिना image bytes और data URL preview देखें.",
          id: "Deteksi byte gambar dan pratinjau data URL tanpa menyalin teks biner.",
          vi: "Nhận diện byte ảnh và xem data URL mà không sao chép văn bản nhị phân.",
          th: "ตรวจ byte รูปและดู data URL โดยไม่ต้องคัดลอก binary text",
          ar: "اكتشف بايتات الصورة وعاين data URL دون نسخ نص ثنائي.",
        }),
      },
      {
        toolSlug: "mime-type-lookup",
        reason: localized({
          en: "Confirm the extension and content type used by the image.",
          ko: "이미지에 맞는 확장자와 content type을 확인합니다.",
          ja: "画像に合う拡張子とcontent typeを確認します。",
          "zh-CN": "确认图片使用的扩展名和 content type。",
          "zh-TW": "確認圖片使用的副檔名與 content type。",
          es: "Confirma extension y content type de la imagen.",
          "pt-BR": "Confirme extensao e content type da imagem.",
          de: "Pruefe Erweiterung und Content-Type des Bildes.",
          fr: "Confirmez l'extension et le content type de l'image.",
          hi: "image की extension और content type जांचें.",
          id: "Pastikan ekstensi dan content type gambar.",
          vi: "Xác nhận đuôi file và content type của ảnh.",
          th: "ยืนยัน extension และ content type ของรูป",
          ar: "تأكد من الامتداد وcontent type للصورة.",
        }),
      },
      {
        toolSlug: "color-converter",
        reason: localized({
          en: "Check contrast when the image is used in a QR, badge, or document background.",
          ko: "이미지가 QR, badge, 문서 배경에 쓰일 때 대비를 확인합니다.",
          ja: "画像をQR、badge、文書背景で使う前にコントラストを確認します。",
          "zh-CN": "图片用于 QR、badge 或文档背景时检查对比度。",
          "zh-TW": "圖片用於 QR、badge 或文件背景時檢查對比。",
          es: "Revisa contraste si la imagen se usa en QR, badge o fondo de documento.",
          "pt-BR": "Revise contraste quando a imagem for usada em QR, badge ou fundo de documento.",
          de: "Pruefe Kontrast, wenn das Bild in QR, Badge oder Dokumenthintergrund landet.",
          fr: "Verifiez le contraste si l'image sert a un QR, badge ou fond de document.",
          hi: "image QR, badge या document background में हो तो contrast जांचें.",
          id: "Cek kontras saat gambar dipakai di QR, badge, atau latar dokumen.",
          vi: "Kiểm tra tương phản khi ảnh dùng trong QR, badge hoặc nền tài liệu.",
          th: "ตรวจ contrast เมื่อรูปใช้ใน QR, badge หรือพื้นหลังเอกสาร",
          ar: "افحص التباين عند استخدام الصورة في QR أو badge أو خلفية مستند.",
        }),
      },
    ],
  },
  {
    slug: "check-dns-deployment",
    title: localized({
      en: "Check a DNS deployment",
      ko: "DNS 배포 확인",
      ja: "DNSデプロイを確認",
      "zh-CN": "检查 DNS 发布",
      "zh-TW": "檢查 DNS 部署",
      es: "Revisar despliegue DNS",
      "pt-BR": "Verificar deploy DNS",
      de: "DNS-Deployment pruefen",
      fr: "Verifier un deploiement DNS",
      hi: "DNS deployment जांचें",
      id: "Cek deployment DNS",
      vi: "Kiểm tra triển khai DNS",
      th: "ตรวจ DNS deployment",
      ar: "فحص نشر DNS",
    }),
    description: localized({
      en: "Verify records, HTTP reachability, sitemap exposure, and robots rules after a domain change.",
      ko: "도메인 변경 후 레코드, HTTP 접근, sitemap 노출, robots 규칙을 확인합니다.",
      ja: "ドメイン変更後のrecord、HTTP到達性、sitemap、robotsルールを確認します。",
      "zh-CN": "域名变更后检查记录、HTTP 可达性、sitemap 和 robots 规则。",
      "zh-TW": "網域變更後檢查紀錄、HTTP 可達性、sitemap 與 robots 規則。",
      es: "Verifica registros, alcance HTTP, sitemap y reglas robots tras cambiar dominio.",
      "pt-BR": "Verifique registros, alcance HTTP, sitemap e regras robots apos mudar dominio.",
      de: "Pruefe Records, HTTP-Erreichbarkeit, Sitemap und robots-Regeln nach Domain-Aenderungen.",
      fr: "Verifiez records, acces HTTP, sitemap et regles robots apres changement de domaine.",
      hi: "domain बदलने के बाद records, HTTP, sitemap और robots rules जांचें.",
      id: "Periksa record, akses HTTP, sitemap, dan aturan robots setelah perubahan domain.",
      vi: "Kiểm tra record, HTTP, sitemap và robots sau khi đổi domain.",
      th: "ตรวจ record, HTTP, sitemap และ robots หลังเปลี่ยน domain",
      ar: "تحقق من records وHTTP وsitemap وrobots بعد تغيير النطاق.",
    }),
    searchIntents: ["dns propagation checklist", "dns deployment checker", "dns deployment checklist", "dmarc checker", "name server checker", "ipv6 dns checker", "domain deployment check", "www apex dns", "sitemap robots check"],
    steps: [
      { toolSlug: "dns-lookup", reason: localized({
        en: "Check A, AAAA, CNAME, MX, TXT, and NS records.",
        ko: "A, AAAA, CNAME, MX, TXT, NS 레코드를 확인합니다.",
        ja: "A、AAAA、CNAME、MX、TXT、NSレコードを確認します。",
        "zh-CN": "检查 A、AAAA、CNAME、MX、TXT、NS 记录。",
        "zh-TW": "檢查 A、AAAA、CNAME、MX、TXT、NS 紀錄。",
        es: "Revisa registros A, AAAA, CNAME, MX, TXT y NS.",
        "pt-BR": "Revise registros A, AAAA, CNAME, MX, TXT e NS.",
        de: "Pruefe A-, AAAA-, CNAME-, MX-, TXT- und NS-Records.",
        fr: "Verifiez les records A, AAAA, CNAME, MX, TXT et NS.",
        hi: "A, AAAA, CNAME, MX, TXT और NS records जांचें.",
        id: "Cek record A, AAAA, CNAME, MX, TXT, dan NS.",
        vi: "Kiểm tra record A, AAAA, CNAME, MX, TXT và NS.",
        th: "ตรวจ record A, AAAA, CNAME, MX, TXT และ NS",
        ar: "افحص سجلات A وAAAA وCNAME وMX وTXT وNS.",
      }) },
      { toolSlug: "http-status-checker", reason: localized({
        en: "Confirm the public URL returns the expected status.",
        ko: "공개 URL이 예상한 status를 반환하는지 확인합니다.",
        ja: "公開URLが期待するstatusを返すか確認します。",
        "zh-CN": "确认公开 URL 返回预期 status。",
        "zh-TW": "確認公開 URL 回傳預期 status。",
        es: "Confirma que la URL publica devuelva el status esperado.",
        "pt-BR": "Confirme se a URL publica retorna o status esperado.",
        de: "Pruefe, ob die oeffentliche URL den erwarteten Status liefert.",
        fr: "Confirmez que l'URL publique renvoie le status attendu.",
        hi: "public URL expected status देता है या नहीं देखें.",
        id: "Pastikan URL publik memberi status yang diharapkan.",
        vi: "Xác nhận URL công khai trả về status mong đợi.",
        th: "ยืนยัน URL สาธารณะคืน status ที่คาดไว้",
        ar: "تأكد أن الرابط العام يرجع status المتوقع.",
      }) },
      { toolSlug: "sitemap-generator", reason: localized({
        en: "Prepare clean sitemap URLs after routing is stable.",
        ko: "라우팅이 안정된 뒤 깨끗한 sitemap URL을 준비합니다.",
        ja: "ルーティング安定後にsitemap URLを整えます。",
        "zh-CN": "路由稳定后准备干净的 sitemap URL。",
        "zh-TW": "路由穩定後準備乾淨的 sitemap URL。",
        es: "Prepara URLs limpias de sitemap cuando el routing este estable.",
        "pt-BR": "Prepare URLs limpas de sitemap quando o roteamento estiver estavel.",
        de: "Bereite saubere Sitemap-URLs vor, sobald Routing stabil ist.",
        fr: "Preparez des URLs sitemap propres lorsque le routage est stable.",
        hi: "routing stable होने के बाद साफ sitemap URLs बनाएं.",
        id: "Siapkan URL sitemap bersih setelah routing stabil.",
        vi: "Chuẩn bị URL sitemap sạch sau khi routing ổn định.",
        th: "เตรียม sitemap URL ที่สะอาดเมื่อ routing เสถียร",
        ar: "جهز روابط sitemap نظيفة بعد استقرار التوجيه.",
      }) },
    ],
  },
  {
    slug: "create-wifi-qr",
    title: localized({
      en: "Create a Wi-Fi QR",
      ko: "Wi-Fi QR 만들기",
      ja: "Wi-Fi QRを作成",
      "zh-CN": "创建 Wi-Fi QR",
      "zh-TW": "建立 Wi-Fi QR",
      es: "Crear QR de Wi-Fi",
      "pt-BR": "Criar QR de Wi-Fi",
      de: "Wi-Fi-QR erstellen",
      fr: "Creer un QR Wi-Fi",
      hi: "Wi-Fi QR बनाएं",
      id: "Buat QR Wi-Fi",
      vi: "Tạo QR Wi-Fi",
      th: "สร้าง Wi-Fi QR",
      ar: "إنشاء QR للواي فاي",
    }),
    description: localized({
      en: "Generate a compatible network password, build the Wi-Fi payload, and check contrast before sharing.",
      ko: "호환되는 네트워크 비밀번호를 만들고 Wi-Fi payload를 구성한 뒤 대비를 확인합니다.",
      ja: "互換性のあるネットワークパスワードを作り、Wi-Fi payloadを組み立て、共有前にコントラストを確認します。",
      "zh-CN": "生成兼容的网络密码，构建 Wi-Fi payload，并在分享前检查对比度。",
      "zh-TW": "產生相容的網路密碼，建立 Wi-Fi payload，分享前檢查對比。",
      es: "Genera una contrasena compatible, arma el payload Wi-Fi y revisa contraste.",
      "pt-BR": "Gere uma senha compativel, monte o payload Wi-Fi e revise contraste.",
      de: "Erzeuge ein kompatibles Netzwerkpasswort, baue den Wi-Fi-Payload und pruefe Kontrast.",
      fr: "Generez un mot de passe compatible, construisez le payload Wi-Fi et verifiez le contraste.",
      hi: "compatible network password बनाएं, Wi-Fi payload तैयार करें और contrast जांचें.",
      id: "Buat kata sandi jaringan, susun payload Wi-Fi, lalu cek kontras.",
      vi: "Tạo mật khẩu mạng, dựng payload Wi-Fi và kiểm tra tương phản.",
      th: "สร้างรหัสผ่านเครือข่าย ประกอบ Wi-Fi payload แล้วตรวจ contrast",
      ar: "انشئ كلمة مرور شبكة مناسبة وابن payload للواي فاي وافحص التباين.",
    }),
    searchIntents: ["wifi qr code generator", "wifi password qr", "qr code size", "qr quiet zone", "qr code contrast", "network qr workflow"],
    steps: [
      { toolSlug: "password-generator", reason: localized({
        en: "Generate a password that fits the router policy.",
        ko: "공유기 정책에 맞는 비밀번호를 생성합니다.",
        ja: "ルーターのポリシーに合うパスワードを生成します。",
        "zh-CN": "生成符合路由器策略的密码。",
        "zh-TW": "產生符合路由器規則的密碼。",
        es: "Genera una contrasena que encaje con la politica del router.",
        "pt-BR": "Gere uma senha que siga a politica do roteador.",
        de: "Erzeuge ein Passwort passend zur Router-Richtlinie.",
        fr: "Generez un mot de passe compatible avec la politique du routeur.",
        hi: "router policy के अनुसार password बनाएं.",
        id: "Buat kata sandi sesuai kebijakan router.",
        vi: "Tạo mật khẩu phù hợp chính sách router.",
        th: "สร้างรหัสผ่านที่ตรงกับ policy ของ router",
        ar: "انشئ كلمة مرور توافق سياسة الراوتر.",
      }) },
      { toolSlug: "qr-code-generator", reason: localized({
        en: "Build the Wi-Fi payload and download the QR image.",
        ko: "Wi-Fi payload를 만들고 QR 이미지를 내려받습니다.",
        ja: "Wi-Fi payloadを作りQR画像をダウンロードします。",
        "zh-CN": "构建 Wi-Fi payload 并下载 QR 图片。",
        "zh-TW": "建立 Wi-Fi payload 並下載 QR 圖片。",
        es: "Arma el payload Wi-Fi y descarga la imagen QR.",
        "pt-BR": "Monte o payload Wi-Fi e baixe a imagem QR.",
        de: "Baue den Wi-Fi-Payload und lade das QR-Bild herunter.",
        fr: "Construisez le payload Wi-Fi et telechargez l'image QR.",
        hi: "Wi-Fi payload बनाएं और QR image डाउनलोड करें.",
        id: "Susun payload Wi-Fi dan unduh gambar QR.",
        vi: "Dựng payload Wi-Fi và tải ảnh QR.",
        th: "ประกอบ Wi-Fi payload และดาวน์โหลดภาพ QR",
        ar: "ابن payload للواي فاي وحمل صورة QR.",
      }) },
      { toolSlug: "color-converter", reason: localized({
        en: "Check foreground and background contrast before printing.",
        ko: "출력 전에 전경/배경 대비를 확인합니다.",
        ja: "印刷前に前景色と背景色のコントラストを確認します。",
        "zh-CN": "打印前检查前景和背景对比度。",
        "zh-TW": "列印前檢查前景與背景對比。",
        es: "Revisa contraste de frente y fondo antes de imprimir.",
        "pt-BR": "Revise contraste de frente e fundo antes de imprimir.",
        de: "Pruefe Vorder- und Hintergrundkontrast vor dem Drucken.",
        fr: "Verifiez le contraste avant-plan/arriere-plan avant impression.",
        hi: "print से पहले foreground और background contrast जांचें.",
        id: "Cek kontras depan dan latar sebelum dicetak.",
        vi: "Kiểm tra tương phản trước khi in.",
        th: "ตรวจ contrast ระหว่าง foreground/background ก่อนพิมพ์",
        ar: "افحص تباين المقدمة والخلفية قبل الطباعة.",
      }) },
    ],
  },
  {
    slug: "generate-secure-token",
    title: localized({
      en: "Generate a secure token",
      ko: "보안 토큰 생성",
      ja: "安全なトークンを生成",
      "zh-CN": "生成安全 token",
      "zh-TW": "產生安全 token",
      es: "Generar token seguro",
      "pt-BR": "Gerar token seguro",
      de: "Sicheren Token erzeugen",
      fr: "Generer un token securise",
      hi: "secure token बनाएं",
      id: "Buat token aman",
      vi: "Tạo token an toàn",
      th: "สร้าง token ที่ปลอดภัย",
      ar: "إنشاء رمز آمن",
    }),
    description: localized({
      en: "Create random session/API/CSRF values, compare hashes, and choose identifiers deliberately.",
      ko: "session/API/CSRF 값을 만들고 hash를 비교하며 식별자를 의도에 맞게 고릅니다.",
      ja: "session/API/CSRF値を作り、hashを比較し、識別子を用途に合わせて選びます。",
      "zh-CN": "创建 session/API/CSRF 值，比较 hash，并按用途选择标识符。",
      "zh-TW": "建立 session/API/CSRF 值，比對 hash，並依用途選擇識別符。",
      es: "Crea valores session/API/CSRF, compara hashes y elige identificadores con cuidado.",
      "pt-BR": "Crie valores session/API/CSRF, compare hashes e escolha identificadores com cuidado.",
      de: "Erzeuge Session/API/CSRF-Werte, vergleiche Hashes und waehle IDs bewusst.",
      fr: "Creez des valeurs session/API/CSRF, comparez les hashes et choisissez les identifiants.",
      hi: "session/API/CSRF values बनाएं, hashes मिलाएं और identifiers सही चुनें.",
      id: "Buat nilai session/API/CSRF, bandingkan hash, dan pilih identifier dengan sadar.",
      vi: "Tạo giá trị session/API/CSRF, so sánh hash và chọn định danh đúng mục đích.",
      th: "สร้างค่า session/API/CSRF เทียบ hash และเลือก identifier ให้เหมาะ",
      ar: "انشئ قيم session/API/CSRF وقارن hashes واختر المعرفات بعناية.",
    }),
    searchIntents: ["csrf token generator", "api key generator", "secure random token", "uuid vs token"],
    steps: [
      { toolSlug: "random-token-generator", reason: localized({
        en: "Generate URL-safe session, API, CSRF, or webhook tokens.",
        ko: "URL-safe session, API, CSRF, webhook 토큰을 생성합니다.",
        ja: "URL-safeなsession、API、CSRF、webhook tokenを生成します。",
        "zh-CN": "生成 URL-safe 的 session、API、CSRF 或 webhook token。",
        "zh-TW": "產生 URL-safe 的 session、API、CSRF 或 webhook token。",
        es: "Genera tokens URL-safe para session, API, CSRF o webhook.",
        "pt-BR": "Gere tokens URL-safe para session, API, CSRF ou webhook.",
        de: "Erzeuge URL-sichere Session-, API-, CSRF- oder Webhook-Tokens.",
        fr: "Generez des tokens URL-safe pour session, API, CSRF ou webhook.",
        hi: "URL-safe session, API, CSRF या webhook tokens बनाएं.",
        id: "Buat token URL-safe untuk session, API, CSRF, atau webhook.",
        vi: "Tạo token URL-safe cho session, API, CSRF hoặc webhook.",
        th: "สร้าง token แบบ URL-safe สำหรับ session, API, CSRF หรือ webhook",
        ar: "انشئ tokens آمنة للروابط للجلسات وAPI وCSRF وwebhook.",
      }) },
      { toolSlug: "hash-generator", reason: localized({
        en: "Compare digest or HMAC output for signatures.",
        ko: "서명에 필요한 digest나 HMAC 결과를 비교합니다.",
        ja: "署名に必要なdigestやHMAC出力を比較します。",
        "zh-CN": "比较签名所需的 digest 或 HMAC 输出。",
        "zh-TW": "比較簽章所需的 digest 或 HMAC 輸出。",
        es: "Compara digest o salida HMAC para firmas.",
        "pt-BR": "Compare digest ou saida HMAC para assinaturas.",
        de: "Vergleiche Digest- oder HMAC-Ausgaben fuer Signaturen.",
        fr: "Comparez digest ou sortie HMAC pour les signatures.",
        hi: "signatures के लिए digest या HMAC output मिलाएं.",
        id: "Bandingkan digest atau output HMAC untuk signature.",
        vi: "So sánh digest hoặc HMAC cho chữ ký.",
        th: "เทียบ digest หรือ HMAC output สำหรับ signature",
        ar: "قارن digest أو ناتج HMAC للتواقيع.",
      }) },
      { toolSlug: "uuid-generator", reason: localized({
        en: "Use UUIDs for identifiers, not as secrets.",
        ko: "UUID는 secret이 아니라 식별자로 사용합니다.",
        ja: "UUIDはsecretではなく識別子として使います。",
        "zh-CN": "UUID 用作标识符，不当作 secret。",
        "zh-TW": "UUID 用作識別符，不當作 secret。",
        es: "Usa UUID como identificadores, no como secretos.",
        "pt-BR": "Use UUIDs como identificadores, nao como segredos.",
        de: "Nutze UUIDs als Bezeichner, nicht als Secrets.",
        fr: "Utilisez les UUID comme identifiants, pas comme secrets.",
        hi: "UUID को secret नहीं, identifier की तरह इस्तेमाल करें.",
        id: "Gunakan UUID sebagai identifier, bukan secret.",
        vi: "Dùng UUID làm định danh, không dùng như secret.",
        th: "ใช้ UUID เป็น identifier ไม่ใช่ secret",
        ar: "استخدم UUID كمعرفات وليس كاسرار.",
      }) },
    ],
  },
  {
    slug: "review-security-headers",
    title: localized({
      en: "Review security headers",
      ko: "보안 헤더 점검",
      ja: "セキュリティヘッダーを確認",
      "zh-CN": "检查安全响应头",
      "zh-TW": "檢查安全回應標頭",
      es: "Revisar headers de seguridad",
      "pt-BR": "Revisar headers de seguranca",
      de: "Security-Header pruefen",
      fr: "Verifier les en-tetes securite",
      hi: "सुरक्षा headers जांचें",
      id: "Periksa header keamanan",
      vi: "Kiểm tra header bảo mật",
      th: "ตรวจ header ความปลอดภัย",
      ar: "مراجعة رؤوس الأمان",
    }),
    description: localized({
      en: "Check response headers, draft a CSP, then confirm the URL and DNS target are the site you meant to protect.",
      ko: "응답 헤더와 CSP 초안을 확인한 뒤 보호하려는 URL과 DNS 대상이 맞는지 검증합니다.",
      ja: "レスポンスヘッダーとCSP案を確認し、保護対象のURLとDNS先が正しいか検証します。",
      "zh-CN": "检查响应头和 CSP 草稿，再确认 URL 与 DNS 目标就是要保护的站点。",
      "zh-TW": "檢查回應標頭與 CSP 草稿，再確認 URL 與 DNS 目標就是要保護的網站。",
      es: "Revisa headers, prepara un CSP y confirma que la URL y DNS sean el sitio correcto.",
      "pt-BR": "Revise headers, rascunhe um CSP e confirme se URL e DNS sao o site certo.",
      de: "Pruefe Response-Header, entwirf CSP und bestaetige URL sowie DNS-Ziel.",
      fr: "Controlez les en-tetes, preparez un CSP et confirmez l'URL et la cible DNS.",
      hi: "response headers देखें, CSP draft बनाएं और URL/DNS target सही है या नहीं जांचें.",
      id: "Cek header respons, susun CSP, lalu pastikan URL dan target DNS benar.",
      vi: "Kiểm tra header phản hồi, soạn CSP và xác nhận URL cùng DNS đúng mục tiêu.",
      th: "ตรวจ header ของ response ร่าง CSP แล้วเช็ก URL และ DNS target ให้ถูกต้อง",
      ar: "افحص رؤوس الاستجابة واكتب مسودة CSP ثم تأكد من الرابط وهدف DNS.",
    }),
    searchIntents: ["security headers checker", "security response header checker", "content security policy generator", "csp header generator", "http headers parser", "strict transport security check", "hsts checker", "x content type options checker", "referrer policy checker"],
    steps: [
      { toolSlug: "http-status-checker", reason: localized({
        en: "Inspect status, redirects, pasted headers, and CSP warnings in one surface.",
        ko: "status, redirect, 붙여 넣은 header, CSP 경고를 한 화면에서 봅니다.",
        ja: "status、redirect、貼り付けたheader、CSP警告を一画面で確認します。",
        "zh-CN": "在同一界面检查 status、redirect、粘贴的 header 和 CSP 警告。",
        "zh-TW": "在同一介面檢查 status、redirect、貼上的 header 與 CSP 警告。",
        es: "Inspecciona status, redirecciones, headers pegados y avisos CSP.",
        "pt-BR": "Inspecione status, redirecionamentos, headers colados e avisos CSP.",
        de: "Pruefe Status, Redirects, eingefuegte Header und CSP-Warnungen.",
        fr: "Inspectez status, redirections, en-tetes colles et alertes CSP.",
        hi: "status, redirects, pasted headers और CSP warnings साथ देखें.",
        id: "Periksa status, redirect, header tempel, dan peringatan CSP.",
        vi: "Kiểm tra status, redirect, header đã dán và cảnh báo CSP.",
        th: "ตรวจ status, redirect, header ที่วาง และ warning ของ CSP",
        ar: "افحص status وredirect والرؤوس الملصقة وتحذيرات CSP.",
      }) },
      { toolSlug: "url-parser", reason: localized({
        en: "Separate origin, path, query, and tracking parameters before writing policies.",
        ko: "정책을 쓰기 전에 origin, path, query, tracking parameter를 분리합니다.",
        ja: "ポリシーを書く前にorigin、path、query、tracking parameterを分けます。",
        "zh-CN": "编写策略前拆分 origin、path、query 和跟踪参数。",
        "zh-TW": "撰寫策略前拆分 origin、path、query 與追蹤參數。",
        es: "Separa origin, ruta, query y parametros de tracking antes de crear politicas.",
        "pt-BR": "Separe origin, path, query e parametros de tracking antes da politica.",
        de: "Trenne Origin, Pfad, Query und Tracking-Parameter vor Policies.",
        fr: "Separez origin, chemin, query et tracking avant les politiques.",
        hi: "policy लिखने से पहले origin, path, query और tracking params अलग करें.",
        id: "Pisahkan origin, path, query, dan parameter tracking sebelum membuat kebijakan.",
        vi: "Tách origin, path, query và tham số tracking trước khi viết chính sách.",
        th: "แยก origin, path, query และ tracking parameter ก่อนเขียน policy",
        ar: "افصل origin وpath وquery ومعلمات التتبع قبل كتابة السياسات.",
      }) },
      { toolSlug: "dns-lookup", reason: localized({
        en: "Confirm the hostname resolves to the deployment you are reviewing.",
        ko: "검토 중인 hostname이 실제 배포 대상으로 해석되는지 확인합니다.",
        ja: "確認中のhostnameが対象デプロイへ解決されるか確認します。",
        "zh-CN": "确认 hostname 解析到正在检查的部署。",
        "zh-TW": "確認 hostname 解析到正在檢查的部署。",
        es: "Confirma que el hostname resuelva al despliegue revisado.",
        "pt-BR": "Confirme se o hostname resolve para o deploy revisado.",
        de: "Bestaetige, dass der Hostname auf das gepruefte Deployment zeigt.",
        fr: "Confirmez que le hostname pointe vers le deploiement examine.",
        hi: "hostname उसी deployment पर resolve हो रहा है या नहीं जांचें.",
        id: "Pastikan hostname mengarah ke deployment yang sedang diperiksa.",
        vi: "Xác nhận hostname trỏ tới bản triển khai đang kiểm tra.",
        th: "ยืนยัน hostname resolve ไปยัง deployment ที่กำลังตรวจ",
        ar: "تأكد أن hostname يشير إلى النشر الذي تراجعه.",
      }) },
    ],
  },
  {
    slug: "validate-deploy-config",
    title: localized({
      en: "Validate deploy config",
      ko: "배포 설정 검증",
      ja: "デプロイ設定を検証",
      "zh-CN": "验证部署配置",
      "zh-TW": "驗證部署設定",
      es: "Validar config de despliegue",
      "pt-BR": "Validar config de deploy",
      de: "Deployment-Konfig pruefen",
      fr: "Valider la config de deploiement",
      hi: "deploy config जांचें",
      id: "Validasi config deployment",
      vi: "Xác thực cấu hình triển khai",
      th: "ตรวจ config สำหรับ deploy",
      ar: "التحقق من إعدادات النشر",
    }),
    description: localized({
      en: "Validate YAML or Compose structure, inspect environment values, then format JSON config fragments before shipping.",
      ko: "YAML이나 Compose 구조를 검증하고 환경 값을 확인한 뒤 배포 전 JSON 설정 조각을 정리합니다.",
      ja: "YAMLやCompose構造を検証し、環境値を確認して、出荷前にJSON設定片を整えます。",
      "zh-CN": "验证 YAML 或 Compose 结构，检查环境值，再整理发布前的 JSON 配置片段。",
      "zh-TW": "驗證 YAML 或 Compose 結構，檢查環境值，再整理發布前的 JSON 設定片段。",
      es: "Valida YAML o Compose, revisa variables de entorno y formatea JSON antes de publicar.",
      "pt-BR": "Valide YAML ou Compose, revise variaveis de ambiente e formate JSON antes do deploy.",
      de: "Validiere YAML oder Compose, pruefe Env-Werte und formatiere JSON vor dem Release.",
      fr: "Validez YAML ou Compose, controlez les variables et formatez le JSON avant livraison.",
      hi: "YAML या Compose structure जांचें, env values देखें और release से पहले JSON config format करें.",
      id: "Validasi YAML atau Compose, cek nilai environment, lalu rapikan JSON sebelum rilis.",
      vi: "Xác thực YAML hoặc Compose, kiểm tra biến môi trường rồi định dạng JSON trước khi phát hành.",
      th: "ตรวจโครงสร้าง YAML หรือ Compose เช็กค่า environment แล้วจัด JSON config ก่อนปล่อยงาน",
      ar: "تحقق من YAML أو Compose وافحص قيم البيئة ثم نسق JSON قبل النشر.",
    }),
    searchIntents: ["docker compose validator", "compose yaml validator", "yaml config checker", "env parser validator", "deployment config checker"],
    steps: [
      { toolSlug: "yaml-validator", reason: localized({
        en: "Check indentation, YAML parse errors, and Compose service diagnostics.",
        ko: "들여쓰기, YAML parse 오류, Compose service 진단을 확인합니다.",
        ja: "インデント、YAML parseエラー、Compose service診断を確認します。",
        "zh-CN": "检查缩进、YAML parse 错误和 Compose service 诊断。",
        "zh-TW": "檢查縮排、YAML parse 錯誤與 Compose service 診斷。",
        es: "Revisa indentacion, errores YAML y diagnostico de servicios Compose.",
        "pt-BR": "Revise indentacao, erros YAML e diagnostico de services Compose.",
        de: "Pruefe Einrueckung, YAML-Parsefehler und Compose-Service-Diagnostik.",
        fr: "Verifiez indentation, erreurs YAML et diagnostics des services Compose.",
        hi: "indentation, YAML parse errors और Compose service diagnostics जांचें.",
        id: "Cek indentasi, error YAML, dan diagnostik service Compose.",
        vi: "Kiểm tra thụt lề, lỗi YAML và chẩn đoán service Compose.",
        th: "ตรวจ indentation, YAML parse error และ diagnostics ของ Compose service",
        ar: "افحص المسافات واخطاء YAML وتشخيص خدمات Compose.",
      }) },
      { toolSlug: "env-parser-validator", reason: localized({
        en: "Review duplicate, malformed, empty, or secret-like environment values.",
        ko: "중복, malformed, 빈 값, secret처럼 보이는 환경 값을 검토합니다.",
        ja: "重複、malformed、空値、secretらしい環境値を確認します。",
        "zh-CN": "检查重复、格式错误、空值或类似 secret 的环境值。",
        "zh-TW": "檢查重複、格式錯誤、空值或類似 secret 的環境值。",
        es: "Revisa valores duplicados, mal formados, vacios o parecidos a secretos.",
        "pt-BR": "Revise valores duplicados, malformados, vazios ou parecidos com segredo.",
        de: "Pruefe doppelte, fehlerhafte, leere oder secret-aehnliche Env-Werte.",
        fr: "Controlez valeurs dupliquees, mal formees, vides ou sensibles.",
        hi: "duplicate, malformed, empty या secret जैसे env values देखें.",
        id: "Tinjau nilai env duplikat, salah format, kosong, atau mirip secret.",
        vi: "Xem biến env trùng, sai định dạng, rỗng hoặc giống secret.",
        th: "ตรวจค่า env ที่ซ้ำ รูปแบบผิด ว่าง หรือคล้าย secret",
        ar: "راجع قيم البيئة المكررة أو الخاطئة أو الفارغة أو الشبيهة بالاسرار.",
      }) },
      { toolSlug: "json-formatter", reason: localized({
        en: "Format JSON config fragments and inspect shape before copying.",
        ko: "JSON 설정 조각을 정리하고 복사 전 구조를 확인합니다.",
        ja: "JSON設定片を整形し、コピー前に構造を確認します。",
        "zh-CN": "格式化 JSON 配置片段，并在复制前检查结构。",
        "zh-TW": "格式化 JSON 設定片段，並在複製前檢查結構。",
        es: "Formatea fragmentos JSON y revisa la forma antes de copiar.",
        "pt-BR": "Formate trechos JSON e revise a estrutura antes de copiar.",
        de: "Formatiere JSON-Konfigteile und pruefe die Struktur vor dem Kopieren.",
        fr: "Formatez les fragments JSON et verifiez la forme avant copie.",
        hi: "JSON config fragments format करें और copy से पहले shape देखें.",
        id: "Rapikan fragmen JSON dan cek bentuknya sebelum disalin.",
        vi: "Định dạng mảnh JSON và kiểm tra cấu trúc trước khi sao chép.",
        th: "จัด JSON config fragment และตรวจโครงสร้างก่อนคัดลอก",
        ar: "نسق مقاطع JSON وافحص الشكل قبل النسخ.",
      }) },
    ],
  },
  {
    slug: "clean-csv-for-api",
    title: localized({
      en: "Clean CSV for API use",
      ko: "API용 CSV 정리",
      ja: "API向けCSVを整える",
      "zh-CN": "清理用于 API 的 CSV",
      "zh-TW": "清理用於 API 的 CSV",
      es: "Limpiar CSV para API",
      "pt-BR": "Limpar CSV para API",
      de: "CSV fuer API bereinigen",
      fr: "Nettoyer un CSV pour API",
      hi: "API के लिए CSV साफ करें",
      id: "Bersihkan CSV untuk API",
      vi: "Làm sạch CSV cho API",
      th: "จัด CSV สำหรับ API",
      ar: "تنظيف CSV لاستخدام API",
    }),
    description: localized({
      en: "Trim CSV rows, remove duplicates, convert to JSON, and make a quick Markdown table for review.",
      ko: "CSV 행을 다듬고 중복을 제거한 뒤 JSON으로 변환하고 검토용 Markdown 표를 만듭니다.",
      ja: "CSV行を整え、重複を除き、JSONへ変換して確認用Markdown表を作ります。",
      "zh-CN": "整理 CSV 行、移除重复、转换为 JSON，并生成用于检查的 Markdown 表格。",
      "zh-TW": "整理 CSV 列、移除重複、轉換為 JSON，並產生檢查用 Markdown 表格。",
      es: "Limpia filas CSV, quita duplicados, convierte a JSON y crea una tabla Markdown.",
      "pt-BR": "Limpe linhas CSV, remova duplicados, converta para JSON e crie tabela Markdown.",
      de: "Bereinige CSV-Zeilen, entferne Duplikate, wandle in JSON und erstelle eine Markdown-Tabelle.",
      fr: "Nettoyez les lignes CSV, retirez les doublons, convertissez en JSON et creez un tableau Markdown.",
      hi: "CSV rows साफ करें, duplicates हटाएं, JSON बनाएं और review के लिए Markdown table बनाएं.",
      id: "Rapikan baris CSV, hapus duplikat, ubah ke JSON, lalu buat tabel Markdown.",
      vi: "Làm sạch dòng CSV, bỏ trùng, đổi sang JSON và tạo bảng Markdown để rà soát.",
      th: "จัดแถว CSV ลบรายการซ้ำ แปลงเป็น JSON แล้วสร้างตาราง Markdown เพื่อตรวจ",
      ar: "نظف صفوف CSV واحذف التكرار وحولها إلى JSON وأنشئ جدول Markdown للمراجعة.",
    }),
    searchIntents: ["csv cleaner", "csv to json converter", "dedupe csv rows", "markdown table generator", "api payload csv"],
    steps: [
      { toolSlug: "csv-json-converter", reason: localized({
        en: "Trim cells, drop empty rows, detect duplicates, and convert rows to JSON.",
        ko: "셀을 다듬고 빈 행을 제거하며 중복을 찾아 JSON 행으로 변환합니다.",
        ja: "セルを整え、空行を除き、重複を見つけてJSON行へ変換します。",
        "zh-CN": "整理单元格、删除空行、检测重复，并转换为 JSON 行。",
        "zh-TW": "整理儲存格、刪除空列、偵測重複，並轉換為 JSON 列。",
        es: "Recorta celdas, elimina filas vacias, detecta duplicados y convierte a JSON.",
        "pt-BR": "Apare celulas, remova linhas vazias, detecte duplicados e converta para JSON.",
        de: "Trimme Zellen, entferne leere Zeilen, finde Duplikate und wandle in JSON.",
        fr: "Nettoyez cellules, lignes vides, doublons et convertissez les lignes en JSON.",
        hi: "cells trim करें, empty rows हटाएं, duplicates पहचानें और JSON rows बनाएं.",
        id: "Rapikan sel, hapus baris kosong, deteksi duplikat, dan ubah ke JSON.",
        vi: "Cắt khoảng trắng, bỏ dòng rỗng, phát hiện trùng và đổi hàng sang JSON.",
        th: "trim cell ลบแถวว่าง ตรวจซ้ำ และแปลงแถวเป็น JSON",
        ar: "قص الخلايا واحذف الصفوف الفارغة واكتشف التكرار وحول الصفوف إلى JSON.",
      }) },
      { toolSlug: "text-sort-dedupe", reason: localized({
        en: "Sort or dedupe key lists before they become API payload values.",
        ko: "API payload 값이 되기 전 key 목록을 정렬하거나 중복 제거합니다.",
        ja: "API payload値にする前にキー一覧を並べ替え、重複を除きます。",
        "zh-CN": "在变成 API payload 值前排序或去重 key 列表。",
        "zh-TW": "在成為 API payload 值前排序或去重 key 清單。",
        es: "Ordena o deduplica listas de claves antes de usarlas en payloads.",
        "pt-BR": "Ordene ou remova duplicados de listas antes de virar payload.",
        de: "Sortiere oder dedupliziere Key-Listen vor API-Payloads.",
        fr: "Triez ou dedupliquez les listes avant de les utiliser dans un payload.",
        hi: "API payload values बनने से पहले key lists sort या dedupe करें.",
        id: "Urutkan atau hapus duplikat daftar key sebelum menjadi payload API.",
        vi: "Sắp xếp hoặc bỏ trùng danh sách key trước khi đưa vào payload API.",
        th: "sort หรือ dedupe รายการ key ก่อนใช้เป็นค่า payload ของ API",
        ar: "رتب أو احذف تكرار قوائم المفاتيح قبل استخدامها في payload API.",
      }) },
      { toolSlug: "markdown-previewer", reason: localized({
        en: "Create a Markdown table so teammates can review the cleaned data quickly.",
        ko: "정리된 데이터를 팀원이 빠르게 검토할 수 있도록 Markdown 표로 만듭니다.",
        ja: "整理済みデータをチームで素早く確認できるMarkdown表にします。",
        "zh-CN": "生成 Markdown 表格，方便团队快速检查清理后的数据。",
        "zh-TW": "產生 Markdown 表格，方便團隊快速檢查清理後的資料。",
        es: "Crea una tabla Markdown para revisar los datos limpios con el equipo.",
        "pt-BR": "Crie uma tabela Markdown para revisar os dados limpos com o time.",
        de: "Erstelle eine Markdown-Tabelle fuer schnelle Teampruefung.",
        fr: "Creez un tableau Markdown pour relire vite les donnees nettoyees.",
        hi: "clean data को teammates के review के लिए Markdown table में बदलें.",
        id: "Buat tabel Markdown agar tim cepat meninjau data yang sudah bersih.",
        vi: "Tạo bảng Markdown để đồng đội rà soát dữ liệu đã làm sạch nhanh hơn.",
        th: "สร้างตาราง Markdown เพื่อให้ทีมตรวจข้อมูลที่จัดแล้วได้เร็ว",
        ar: "أنشئ جدول Markdown ليراجع الفريق البيانات النظيفة بسرعة.",
      }) },
    ],
  },
];

function localizeRecipe(recipe: WorkflowRecipe, locale: Locale, tools: ToolDefinition[]): LocalizedWorkflowRecipe | undefined {
  const toolBySlug = new Map(tools.map((tool) => [tool.slug, tool]));
  const steps = recipe.steps
    .map((step) => {
      const tool = toolBySlug.get(step.toolSlug);
      if (!tool) return undefined;
      return { tool, reason: text(step.reason, locale) };
    })
    .filter((step): step is LocalizedWorkflowStep => Boolean(step));

  if (steps.length < 2) return undefined;
  return {
    slug: recipe.slug,
    title: text(recipe.title, locale),
    description: text(recipe.description, locale),
    searchIntents: recipe.searchIntents,
    steps,
  };
}

export function getLocalizedWorkflowRecipes(locale: Locale, tools: ToolDefinition[]) {
  return workflowRecipes
    .map((recipe) => localizeRecipe(recipe, locale, tools))
    .filter((recipe): recipe is LocalizedWorkflowRecipe => Boolean(recipe));
}

export function getWorkflowRecipesForTool(toolSlug: string, locale: Locale, tools: ToolDefinition[], limit = 3) {
  return getLocalizedWorkflowRecipes(locale, tools)
    .filter((recipe) => recipe.steps.some((step) => step.tool.slug === toolSlug))
    .sort((a, b) => {
      const aIndex = a.steps.findIndex((step) => step.tool.slug === toolSlug);
      const bIndex = b.steps.findIndex((step) => step.tool.slug === toolSlug);
      return aIndex - bIndex || a.title.localeCompare(b.title);
    })
    .slice(0, limit);
}
